### ISSUE TITLE
dunst displays notifications over xscreensaver

### ISSUE THREAD

**Issue by Abbotta4** [dunst-project/dunst#1235] opened 2023-11-22 13:05 UTC
### Issue description

dunst displays notifications over xscreensaver when using picom as a compositor, even with `unredir-if-possible = true` in picom.conf as suggested in https://github.com/dunst-project/dunst/issues/553#issuecomment-1188108305. dunst *does not* display notifications over i3lock, though.

### Installation info

- Version: `1.9.2 (2023-04-20)`
- Install type: `package (emerge)`
- Window manager / Desktop environment: `Openbox`
- Distro: `Gentoo`

<details>
<summary>Minimal confs</summary>

reproducible with default dunst: `dunst -config - </dev/null`
reproducible with default picom: `picom --config /dev/null --unredir-if-possible`
</details>

**Comment by Narrat** [comment] 2023-11-23 16:36
Related: https://github.com/dunst-project/dunst/issues/697

**Comment by fwsmit** [comment] 2024-01-01 16:29
Duplicate of #697

**Closed by fwsmit** 2024-01-01 16:29 UTC
