### ISSUE TITLE
Modifying geometry setting with RULES

### ISSUE THREAD

**Issue by machinedgod** [dunst-project/dunst#682] opened 2020-01-16 15:46 UTC
Hi,
I was wondering if it'd be possible to add a feature, to change geometry of the notification window depending on the rule being used? I read through `man` and tested just to make sure, but it seems this isn't possible.

I'd like to be able to set up a class of notifications (such as appointments and "Task done" for long running background tasks) that'd pop up in the middle of the screen.

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.4.1 (2019-07-03)`
- Install type: `package`
- Distro and version: `Arch, 4.19.95-1-lts`

**Comment by tsipinakis** [comment] 2020-01-17 08:54
Closing this as a duplicate of #265.

It's been a long requested feature but it's more complicated than it looks to implement as it requires support and management of multiple different windows.

There has been some work done to cleanup the code to be able to support this but not actual effort into implementation.

**Closed by tsipinakis** 2020-01-17 08:54 UTC
