### ISSUE TITLE
Support for Chrome native notifications

### ISSUE THREAD

**Issue by JesseFarebro** [dunst-project/dunst#375] opened 2017-09-17 20:54 UTC
Just wanted to get a discussion going to see what kind of work would be needed to support Chrome's native notifications. It seems dunst supports most of the capabilities Chrome needs but dunst is still being blacklisted in Chrome.

More discussion can be seen here: https://bugs.chromium.org/p/chromium/issues/detail?id=676220

**Comment by bebehei** [comment] 2017-09-18 17:32
I'd guess chromium behaves the same and I tested it yesterday on chromium:

In general a notification server can [support "capabilites"](https://developer.gnome.org/notification-spec/#commands). In the thread there said, that `action` and `action-icons` is required. But even after activation, chromium does not send the notifications to dunst. Chromium also does not query the capabilites.

Only [forcing chromium helps](http://www.omgubuntu.co.uk/2017/04/google-chrome-dev-lets-enable-native-desktop-notifications) doing this.

**Comment by tsipinakis** [comment] 2017-09-18 17:50
Hm, from what I see in the [source](https://chromium.googlesource.com/chromium/src.git/+/3b10f2dff04fd2af6ca1fc6e23ae2a34f81ccc37/chrome/browser/notifications/notification_platform_bridge_linux.cc#435) the only capabilities required are `body` and `action`

**Comment by bebehei** [comment] 2017-09-18 18:11
@tsipinakis  `dbus-monitor path=/org/freedesktop/Notifications` doesn't even show any activity when launching a notification.

Maybe @hobarrera can tell you more he participated in the thread.

**Comment by hobarrera** [comment] 2017-09-18 22:16
Sorry, there's not much more that I can add.

The patch that does the blacklisting itself is [here](https://codereview.chromium.org/download/issue2886903005_1.diff). My C++ isn't good enough to follow through, but maybe you can find something relevant.

**Comment by hobarrera** [comment] 2017-09-18 22:18
Actually, it seems the capabilities call is done when *launching* chrome, not when showing a notification:


```
$ dbus-monitor path=/org/freedesktop/Notifications                                            
signal time=1505773000.276594 sender=org.freedesktop.DBus -> destination=:1.1082 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.1082"                            
signal time=1505773000.276608 sender=org.freedesktop.DBus -> destination=:1.1082 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.1082"                            
method call time=1505773003.220341 sender=:1.1086 -> destination=org.freedesktop.Notifications serial=3 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetCapabilities
```

**Comment by Tadly** [comment] 2017-09-20 07:21
Wait, so you guys are saying that notifications posted by chrome _should_ not be display via dunst?
Because they do for me.

The two entries starting with `#` are actions and do nothing at all.
Also, the icon is always the generic info icon.

![2017-09-20-091531_1920x1080_scrot](https://user-images.githubusercontent.com/503647/30631477-a2491804-9de4-11e7-8a48-af04241bda7f.png)

p.s. that's chrome 61 but has been working every since google introduced native notifications on linux.

**Comment by tsipinakis** [comment] 2017-09-20 07:39
@JesseFarebro What version are you running can you verify that you're using one that supports native notifications?

@Tadly Can you provide a dbus-monitor dump starting with closed chrome and receiving a notification? Just to have an idea on how chrome behaves from launch to notification sending and actions.

The icon thing may be related to #339 if you're on the latest stable.

**Comment by bebehei** [comment] 2017-09-20 07:43
@Tadly could you also please provide the setting of the flag `chrome://flags/#enable-native-notifications`?

**Comment by Tadly** [comment] 2017-09-20 07:45
@tsipinakis if you tell me how to, sure. Never used any of the dbus tools nor did I ever work with dbus itself. Would save me a lot of time :)

Also, icons do generally work. Chrome is the only one I've noticed it not doing so (I don't get a whole lot of notifications on linux though)

`chrome://flags/#enable-native-notifications` is enabled. I remember doing that now that you mention it :)

**Comment by tsipinakis** [comment] 2017-09-20 07:53
> if you tell me how to, sure

Just close chrome entirely, run `dbus-monitor` in a terminal and then open chrome and send a notification from it.

**Comment by Tadly** [comment] 2017-09-20 08:00
@tsipinakis Didn't know where else to put it but here you go... https://pastebin.com/uS6bJn4q

**Comment by bebehei** [comment] 2017-09-20 08:17
> @bebehei chrome://flags/#enable-native-notifications is enabled. I remember doing that now that you mention it :)

So that's the reason for it. Can you please test, that "default" does not show notifications?

@tsipinakis For me, this looks like an implementation bug of chrome. dunst provides all required caps and it looks like chrome behaves wrong in its "default" behavior.

**Comment by Tadly** [comment] 2017-09-20 08:24
@bebehei Can confirm. Setting it back to default gives me chromes notifications again.

**Comment by JesseFarebro** [comment] 2017-09-23 03:53
@tsipinakis Running Chrome 61, latest version. I do have #enable-native-notifications enabled and when I run `dbus-monitor` while launching chrome there are no queries to dbus for notification capabilities at all. Running latest dunst from master and verified `notify-send` works as expected with the correct dbus queries.

Anything else you can suggest?

**Comment by maximbaz** [comment] 2017-11-11 18:47
> it looks like chrome behaves wrong in its "default" behavior.

Comment from the sources of the last stable chromium:

```
// Selection of the implementation works as follows:
//   - Android always uses the NativeNotificationDisplayService.
//   - Mac uses the NativeNotificationDisplayService by default but
//     can revert to MessageCenterDisplayService via
//     chrome://flags#enable-native-notifications or Finch
//   - Linux uses MessageCenterDisplayService by default but can switch
//     to NativeNotificationDisplayService via
//     chrome://flags#enable-native-notifications
//   - All other platforms always use the MessageCenterDisplayService.
```

So as you can see this behavior is intentional, while Mac uses native notifications for "Default", Linux does not and requires the flag 😞.

---------------

> The icon thing may be related to #339 if you're on the latest stable.

On the latest master the icon is still not showing when notification is sent by chromium (e.g. by [this website](https://www.bennish.net/web-notifications.html)). As it was mentioned, images are present when notifications are sent by other apps, so it must be something to do specifically with chromium.

---------------

@JesseFarebro I noticed that if I run `chromium --enable-native-notifications` then native notifications are not enabled, but if set `#enable-native-notifications` to `Enabled` in `chrome://flags`, then native notifications start working. Not sure why, other flags seem to be working even when passed as CLI argument. Try different ways to set the flag, maybe one of them will work for you.

**Comment by slokhorst** [comment] 2017-12-07 12:29
The flag has been [enabled by default](https://chromium.googlesource.com/chromium/src.git/+/65ffa597151e7a0503fb98d81e0f309ae2e852aa) and will ship in [Chromium 64](https://www.chromestatus.com/feature/5689068222414848).

It still shows the generic Chrome icon when using 64.0.3278.0 (dev channel).

**Comment by slokhorst** [comment] 2017-12-07 12:43
Oops, my bad! With the current Dunst master it even shows the custom notification icon. Everything works perfectly! 

![2017-12-07-134321_708x319_scrot](https://user-images.githubusercontent.com/8083666/33715936-9a852c22-db54-11e7-98d2-a368562b396d.png)

**Comment by bebehei** [comment] 2017-12-07 14:05
@slokhorst Thanks for notifying us. As the feature is now shipping downards the stream and will released at the end of January, I'll close this issue.

The missing icons probably are related to #447. I can say for sure, that a new dunst release is shipped out before chromium.

**Closed by bebehei** 2017-12-07 14:06 UTC
Labels: external
