### ISSUE TITLE
100% CPU usage while notification shown if idle and idle_treshold > 0

### ISSUE THREAD

**Issue by Markus00000** [dunst-project/dunst#169] opened 2014-05-09 13:38 UTC
While I had `idle_threshold = 120` in my `dunstrc`, I regularly came back to my computer with fans at maximum speed and CPU usage at 100% when a notification was shown while idle.

As soon as the notification disappears everything is back to normal.

Version: 1.0.0.584.48de907

**Comment by hughdavenport** [comment] 2015-06-22 00:16
So this may be fixed, and may also be similar to bug @194, so that may also be fixed!

**Comment by Eizen** [comment] 2017-01-14 21:35
Can anyone confirm if this is fixed in latest master?

**Comment by wavexx** [comment] 2017-01-14 22:41
I cannot reproduce this

**Comment by Stebalien** [comment] 2017-01-27 00:45
I can no longer reproduce this.

**Comment by tsipinakis** [comment] 2017-01-27 14:54
I'll close this then, feel free to reopen or create a new issue if it is still a problem.

**Closed by tsipinakis** 2017-01-27 14:54 UTC
Labels: waiting-for

**Comment by mustaqimM** [comment] 2022-08-06 05:33
Hello, I don't if I should open a new issue but I just had this happen to me. Overnight I set files to download and with it unattended, the CPU usage increased for each notification shown. It can be reproduced with multiple entries of `dunstctl history-pop`. With 10 entries shown, it uses 50% CPU of a core non-stop until the notifications are removed.

```zsh
$ dunstctl history
```
<pre>
{
	"type" : "aa{sv}",
	"data" : [
		[
			{
				"body" : {
					"type" : "s",
					"data" : "Connected"
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Headphones</b>\nConnected"
				},
				"summary" : {
					"type" : "s",
					"data" : "Headphones"
				},
				"appname" : {
					"type" : "s",
					"data" : "blueman"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : ""
				},
				"id" : {
					"type" : "i",
					"data" : 14
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1139046024736
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "'' has finished downloading."
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Download completed</b>\n'' has finished downloading."
				},
				"summary" : {
					"type" : "s",
					"data" : "Download completed"
				},
				"appname" : {
					"type" : "s",
					"data" : "qBittorrent"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/apps/qbittorrent.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 31
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1182512410321
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "'' has finished downloading."
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Download completed</b>\n'' has finished downloading."
				},
				"summary" : {
					"type" : "s",
					"data" : "Download completed"
				},
				"appname" : {
					"type" : "s",
					"data" : "qBittorrent"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/apps/qbittorrent.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 30
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1178810042448
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "'' has finished downloading."
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Download completed</b>\n'' has finished downloading."
				},
				"summary" : {
					"type" : "s",
					"data" : "Download completed"
				},
				"appname" : {
					"type" : "s",
					"data" : "qBittorrent"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/apps/qbittorrent.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 29
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1176983901447
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "'' has finished downloading."
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Download completed</b>\n'' has finished downloading."
				},
				"summary" : {
					"type" : "s",
					"data" : "Download completed"
				},
				"appname" : {
					"type" : "s",
					"data" : "qBittorrent"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/apps/qbittorrent.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 28
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1176857567043
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "'' has finished downloading."
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Download completed</b>\n'' has finished downloading."
				},
				"summary" : {
					"type" : "s",
					"data" : "Download completed"
				},
				"appname" : {
					"type" : "s",
					"data" : "qBittorrent"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/apps/qbittorrent.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 27
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1176786183558
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "'' has finished downloading."
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Download completed</b>\n'' has finished downloading."
				},
				"summary" : {
					"type" : "s",
					"data" : "Download completed"
				},
				"appname" : {
					"type" : "s",
					"data" : "qBittorrent"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/apps/qbittorrent.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 26
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1176616089832
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "'' has finished downloading."
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Download completed</b>\n'' has finished downloading."
				},
				"summary" : {
					"type" : "s",
					"data" : "Download completed"
				},
				"appname" : {
					"type" : "s",
					"data" : "qBittorrent"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/apps/qbittorrent.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 25
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1176062649161
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "'' has finished downloading."
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Download completed</b>\n'' has finished downloading."
				},
				"summary" : {
					"type" : "s",
					"data" : "Download completed"
				},
				"appname" : {
					"type" : "s",
					"data" : "qBittorrent"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/apps/qbittorrent.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 24
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1175487129206
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "'' has finished downloading."
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Download completed</b>\n'' has finished downloading."
				},
				"summary" : {
					"type" : "s",
					"data" : "Download completed"
				},
				"appname" : {
					"type" : "s",
					"data" : "qBittorrent"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/apps/qbittorrent.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 23
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1175252035085
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "'' has finished downloading."
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Download completed</b>\n'' has finished downloading."
				},
				"summary" : {
					"type" : "s",
					"data" : "Download completed"
				},
				"appname" : {
					"type" : "s",
					"data" : "qBittorrent"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/apps/qbittorrent.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 22
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1174828043530
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "'' has finished downloading."
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Download completed</b>\n'' has finished downloading."
				},
				"summary" : {
					"type" : "s",
					"data" : "Download completed"
				},
				"appname" : {
					"type" : "s",
					"data" : "qBittorrent"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/apps/qbittorrent.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 21
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1174458074914
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "'' has finished downloading."
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Download completed</b>\n'' has finished downloading."
				},
				"summary" : {
					"type" : "s",
					"data" : "Download completed"
				},
				"appname" : {
					"type" : "s",
					"data" : "qBittorrent"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/apps/qbittorrent.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 20
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1173603154970
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "'' has finished downloading."
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Download completed</b>\n'' has finished downloading."
				},
				"summary" : {
					"type" : "s",
					"data" : "Download completed"
				},
				"appname" : {
					"type" : "s",
					"data" : "qBittorrent"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/apps/qbittorrent.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 19
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1173142328816
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "'' has finished downloading."
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Download completed</b>\n'' has finished downloading."
				},
				"summary" : {
					"type" : "s",
					"data" : "Download completed"
				},
				"appname" : {
					"type" : "s",
					"data" : "qBittorrent"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/apps/qbittorrent.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 18
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1173024170323
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "'' has finished downloading."
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Download completed</b>\n'' has finished downloading."
				},
				"summary" : {
					"type" : "s",
					"data" : "Download completed"
				},
				"appname" : {
					"type" : "s",
					"data" : "qBittorrent"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/apps/qbittorrent.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 17
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1173008092597
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "'' has finished downloading."
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Download completed</b>\n'' has finished downloading."
				},
				"summary" : {
					"type" : "s",
					"data" : "Download completed"
				},
				"appname" : {
					"type" : "s",
					"data" : "qBittorrent"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/apps/qbittorrent.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 16
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1172772500430
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "Disconnected"
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Headphones</b>\nDisconnected"
				},
				"summary" : {
					"type" : "s",
					"data" : "Headphones"
				},
				"appname" : {
					"type" : "s",
					"data" : "blueman"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/devices/audio-headset.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 15
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1141237642609
				},
				"timeout" : {
					"type" : "x",
					"data" : 0
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "Disconnected"
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Headphones</b>\nDisconnected"
				},
				"summary" : {
					"type" : "s",
					"data" : "Headphones"
				},
				"appname" : {
					"type" : "s",
					"data" : "blueman"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/devices/audio-headset.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 12
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1138276123296
				},
				"timeout" : {
					"type" : "x",
					"data" : 10000000
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			},
			{
				"body" : {
					"type" : "s",
					"data" : "Connected to Audio and input profiles on Headphones"
				},
				"message" : {
					"type" : "s",
					"data" : "<b>Connected</b>\nConnected to Audio and input profiles on Headphones"
				},
				"summary" : {
					"type" : "s",
					"data" : "Connected"
				},
				"appname" : {
					"type" : "s",
					"data" : "blueman"
				},
				"category" : {
					"type" : "s",
					"data" : ""
				},
				"default_action_name" : {
					"type" : "s",
					"data" : "default"
				},
				"icon_path" : {
					"type" : "s",
					"data" : "/usr/share/icons/Papirus-Dark/24x24/devices/audio-headset.svg"
				},
				"id" : {
					"type" : "i",
					"data" : 11
				},
				"timestamp" : {
					"type" : "x",
					"data" : 1135867450580
				},
				"timeout" : {
					"type" : "x",
					"data" : 10000000
				},
				"progress" : {
					"type" : "i",
					"data" : -1
				}
			}
		]
	]
}
</pre>

**Comment by Necoro** [comment] 2022-08-09 19:03
@mustaqimM Please open a new issue, that one has been closed for good. The code base has also evolved by a bit, so the issue is probably a different one.
