### ISSUE TITLE
HTML markup doesn't work with notify-send

### ISSUE THREAD

**Issue by catzybluphish** [dunst-project/dunst#667] opened 2019-10-11 16:30 UTC
If I was to run `notify-send "<span color='#ffffff'>File(s) moved /tmp</span>"` in the terminal, it would show that literal text as if markup is disabled, which is actually set to full in my config. Apparently notify-send commands work with markup within them, but I'm not sure. If they don't, is there a workaround instead of directly editing the format setting in the config (which I want to keep for Spotify notifications, etc.)?
My [dunstrc](http://ix.io/1YkY).

### Installation info

- Version: `1.4.1 (2019-07-03)`
- Install type: `package`
- Distro and version: `Arch Linux`

**Comment by tsipinakis** [comment] 2019-10-11 16:37
Hi,
This is a duplicate of #616, please move discussion about it there to avoid having multiple issues. The notification spec didn't 'officially' support markup in the body which ended up breaking many clients. There are a few workarounds mentioned in that issue such as using the body (e.g. `notify-send "-" "<span color='#ffffff'>File(s) moved /tmp</span>"` but I'm open to any ideas on how to improve upon this in order to limit the impact of this change.

Given this has been reported a lot I'll add some more prominent warnings about it to the documentation.

**Closed by tsipinakis** 2019-10-11 16:37 UTC
