### ISSUE TITLE
Dunst rendering digits as emojis when explicitly using an Emoji font.

### ISSUE THREAD

**Issue by molguin92** [dunst-project/dunst#680] opened 2020-01-13 14:33 UTC
Apologies if this has been addressed somewhere else, but I couldn't find any mention of this issue anywhere else (except for an Arch Linux forum post with no comments on it!: https://bbs.archlinux.org/viewtopic.php?id=249760 ).

If an emoji font is explicitly declared as a fallback font in dunstrc, dunst renders all digits as emojis:

- dunstrc: `font = FuraCode Nerd Font, Noto Emoji 10`
- test notification: `notify-send test "test 🤔 1337"`
- dunst output: 
![2020-01-13-152755_164x52_scrot](https://user-images.githubusercontent.com/1755518/72263523-4ea8f780-3619-11ea-96c3-2ff8b6d7aedc.png)

If no explicit emoji fallback font is declared, everything works as expected:

- dunstrc: `font = FuraCode Nerd Font 10`
- dunst output:
![2020-01-13-152903_119x52_scrot](https://user-images.githubusercontent.com/1755518/72263579-6f714d00-3619-11ea-9ecf-73b7ce25341c.png)

Not explicitly declaring an emoji font for dunst shouldn't be a problem if one only has a single emoji font installed, but couldn't it potentially cause issues if more than one emoji-capable fonts are installed on the system?

### Installation info

- Version: `1.4.1`
- Install type: `package`
- Distro and version: `Arch Linux `

**Comment by tsipinakis** [comment] 2020-01-13 19:38
Reproduced, however reversing the order of the fonts so the emoji font is first seems to fix it, weirdly.

**Comment by molguin92** [comment] 2020-01-16 20:11
Sorry about the delay.

I can confirm it works as expected if the font line in dunstrc is set to:
`font = Noto Emoji 10, FuraCode Nerd Font 10`

HOWEVER, if the font size is omitted from the emoji font declaration, the problem returns:
`font = Noto Emoji, FuraCode Nerd Font 10`

The problem also reappears if the font size is specified for both fonts in the original order:
`font = FuraCode Nerd Font 10, Noto Emoji 10`

**Comment by tsipinakis** [comment] 2020-01-17 09:12
My theory: This is the result of pango (our font library) not properly failing when wrong font description syntax is used.

The documentation of the format of the `font` parameter is [here](https://developer.gnome.org/pango/stable/pango-Fonts.html#pango-font-description-from-string).
From that link the format is `[FAMILY-LIST] [STYLE-OPTIONS] [SIZE] [VARIATIONS]`
Where `FAMILY-LIST` is a comma separated list and `STYLE-OPTIONS` is a space separated list

My assumption is that it can't handle spaces in the font name since `font = "Monospace,Noto Color Emoji" 10`, it's probably assuming the first space ends the list.

But I still can't explain why the first example works.

And the bigger takeaway here: This should all be mentioned in the man page.

**Comment by molguin92** [comment] 2020-02-19 20:56
Hi, it's now it stopped working again, even with the previously correct setups. 
Both `font = Noto Emoji 10, FuraCode Nerd Font 10` and `font = "FuraCode Nerd Font,Noto Emoji" 10` now show emojis instead of numbers (which is a bit infuriating tbh). Not specifying the fallback font explicitly still works tho,  `font = FuraCode Nerd Font 10`

The only change I can see in my system is that `pango` was recently updated:
```
# grep -i upgraded /var/log/pacman.log | grep pango
[2020-02-11T10:15:48-0500] [ALPM] upgraded pango (1:1.44.7-1 -> 1:1.44.7+11+g73b46b04-1)
```

**Comment by kajzersoze** [comment] 2020-08-28 16:04
For me it doesn't show color emojis at all
I have them working in terminal, wm, dmenu, but in dunst they don't show, there's just empty space instead of emoji
I tried multiple font combinations, I don't get it

dunst 1.4.1

**Comment by kajzersoze** [comment] 2020-08-29 15:38
Problem is in Pango or Cairo, most likely it's just Pango.
Tried to search what else is using Pango on my system and see if emojis would show up and found that Rofi isn't showing them either.
I have nothing else to try and in all other apps they're fine.
Hmm, too bad that Dunst is using Pango but ok, I doubt I'll switch to something else over this.
[Pango Color Glyphs](https://stackoverflow.com/questions/38064048/pango-color-glyphs)
[emojis dont show up](https://github.com/davatorium/rofi/issues/1042)

**Comment by tsipinakis** [comment] 2020-08-29 20:05
> Problem is in Pango or Cairo, most likely it's just Pango.

Indeed the problem here is all pango - doesn't doesn't do any of the text/font handling it just passes it to pango and lets it do its thing.

If there are any fixes that can be done on the dunst side I'd welcome suggestions/PRs but I doubt there's something that can be done here.

**Comment by kajzersoze** [comment] 2020-08-30 09:14
It puzzles me that you and others in this thread are displaying them at all, never mind the digits issue.
I've tried 3 versions of Pango, 1.42, 1.44 and 1.46
I'm on Gentoo and just tried it on Arch as well, it doesn't show there either.

Can you launch this in terminal please?
It will make pango.png and in my case it doesn't show globe emoji, can you tell me will it render for you ?
Replace the emoji font with the one you want, you'll need imagemagick installed.
```
convert -background pink -size 600x50 -set colorspace sRGB \
pango:"<span font=\"Noto Color Emoji\" size=\"24576\">🌏</span> <span font=\"Noto Color Emoji\" size=\"24576\" color=\"green\">Earth in Traditional</span>" \
pango.png
```

This is what mine looks like :
![20200830-110643](https://user-images.githubusercontent.com/11412353/91655511-5be3fb00-eab1-11ea-852f-1e44a7d662f4.png)
Supposed to be like this :
![20200830-110719](https://user-images.githubusercontent.com/11412353/91655513-5edeeb80-eab1-11ea-9bdf-e9d1b3e04628.png)

[Source](https://www.imagemagick.org/discourse-server/viewtopic.php?t=32897)

**Comment by kajzersoze** [comment] 2020-09-01 09:32
Problem was in my fontconfig (/etc/fonts/local.conf) 

Sorry about noise.

**Comment by BachoSeven** [comment] 2020-09-05 13:44
Hi @kajzersoze, would you be so kind as to indicate how you actually solved your issue with `fontconfig`? I see the same output from your little `one-liner` above; and I don't understand what would be the issue with `fontconfig`, isn't it supposed to use the user's `$XDG_CONFIG_HOME/fontconfig/fonts.conf` rather than the system one in `etc`(?)

Thanks in advance, I have been having this issue for a while now.

**Comment by kajzersoze** [comment] 2020-09-05 14:27
@BachoSeven, hi, sure, I had this inside, when I deleted those line it was ok then.
```
<match target="font">
              <edit mode="assign" name="embeddedbitmap">
                <bool>false</bool>
              </edit>
</match> 
```

**Comment by BachoSeven** [comment] 2020-09-05 14:32
Thank you, that was it! Didn't realise I had those lines, probably copied them from the Arch Wiki thinking it was a sane default.

**Comment by kajzersoze** [comment] 2020-09-05 15:28
You're welcome, glad it worked.
Yeah bizarre really, I've picked it somewhere as well.

**Comment by BachoSeven** [comment] 2020-09-05 15:34
Yea, I don't think I have many other things which would be affected by it; I'm on `dwm` which does not support pango (although there's a patch for it)

I know that people have had problems with `pango` on `i3` for sure.

**Comment by bynect** [comment] 2024-03-01 22:45
Pango by design doesn't allow to specify multiple fonts. To do that you should set up properly fallbacks with fontconfig

**Comment by bynect** [comment] 2024-04-19 08:33
I will close this since the problem is caused by the pango design and we can't do much. This kind of thing can be configured with fontconfig

**Closed by bynect** 2024-04-19 08:33 UTC
