### ISSUE TITLE
Wrongly aligned notifications with shrink=yes

### ISSUE THREAD

**Issue by rddunphy** [dunst-project/dunst#760] opened 2020-09-11 12:11 UTC
When the shrink option is turned on and align is set to center, stacked notifications are not always aligned to the longest notification. (It looks like notifications are aligned to the longest _preceding_ notification, but not aligned to any longer notifications that come later.)

<img src="https://user-images.githubusercontent.com/10012625/92922749-3a2e3080-f42e-11ea-8ac3-d216d53593f0.png" width="200">

**Relevant sections of `dunstrc`:**

```
alignment = center
geometry = "1000x50-15+100"
shrink = yes
```

**Steps to reproduce:**

* Add above to `dunstrc`
* Send a short notification, then a longer notification, then a shorter one again
* Redisplay the notifications from the history with ctrl+grave

**Expected behaviour:**

The top notification should be centred relative to the middle notification, the way the bottom one is.

### Installation info

- Version: `v1.5.0-7-ge59d203`
- Install type: `apt package`
- Distro and version: `Ubuntu with i3 `

**Comment by rddunphy** [comment] 2020-09-16 11:30
> It looks like notifications are aligned to the longest preceding notification, but not aligned to any longer notifications that come later.

I just realised this isn't accurate - each notification is aligned to the longest notification displayed above it; the order in history is irrelevant. (So, when cycling through history with ctrl+grave, the problem occurs with older notifications, but if several notifications come in live it's the newest notifications that are not centred.)

**Comment by tsipinakis** [comment] 2020-09-16 11:34
Thanks for the report! This is a duplicate of #518, so I'll close it. A lot of refactoring is needed to fix this and some other similar issues but due to time constraints I don't know when I'll be able to pick it up.
(Of course, contributions welcome).

**Closed by tsipinakis** 2020-09-16 11:34 UTC

**Comment by rddunphy** [comment] 2020-09-16 16:10
Ah, thanks! Sorry I missed the duplicate.
