### ISSUE TITLE
If window width is 0, I can't set max_icon_size

### ISSUE THREAD

**Issue by Yamboy1** [dunst-project/dunst#640] opened 2019-07-02 21:35 UTC
If I try and set max_icon_size while window width is 0, max_icon_size gets reset to 0

Output from `dunst -print`:
 ```
$ dunst -print
WARNING: Max width was set to 0 but got a max_icon_size of 18, too large to use. Setting max_icon_size=0
```
I'm setting the window width to 0 because i want the notification to not be squished, but I still don't want huge icons.

### Installation info

- Version: `1.4.0 (2019-03-30)`
- Install type: `package`
- Distro and version: `Arch Linux ARM`

**Comment by tsipinakis** [comment] 2019-07-03 06:24
This is a duplicate of #614. Already fixed in master, I'll put out a bugfix release for this and a few other issues shortly.

Thanks for the report either way!

**Closed by tsipinakis** 2019-07-03 06:24 UTC
