### ISSUE TITLE
Notification window not shown on top after restarting the window manager

### ISSUE THREAD

**Issue by blueyed** [dunst-project/dunst#160] opened 2014-03-29 23:22 UTC
I have noticed that dunst notifications are not visible above other clients, after the window manager (awesome) has been restarted.

It seems like dunst only puts its window on top when it creates the first notification, but not for additional ones.

I think a good enough fix might be to put dunst's window on top for every new notification.

**Comment by mgraham** [comment] 2015-05-11 22:15
I'm seeing the not-on-top behaviour as well, but I'm having trouble reproducing it.  It's not related to  restarting my window manager.  It seems to happen after long periods of inactivity.

**Comment by Eizen** [comment] 2017-02-10 00:58
Can anyone confirm if this is still an issue in HEAD?

**Comment by rafaqz** [comment] 2017-02-15 00:04
This is still happening on arch/xmonad. Again its hard to reproduce, but also seems after long periods of inactivity.

**Comment by rafaqz** [comment] 2017-03-07 07:59
I think I have to take that back... This is now only happening to when I have another window maximised. Still an issue but less random.

**Comment by tsipinakis** [comment] 2017-07-09 17:23
This should be fixed on master due to 8b74a756c2a1eaa95120ce8fcf56540f1f29cbb5 can you confirm @rafaqz ?

**Comment by bebehei** [comment] 2018-04-25 14:01
[I've created a small reproducer for the `_NET_WM_STATE_ABOVE`](https://gist.github.com/bebehei/bf5204254b3d64c9d5468f75b6ca73d8).

On awesomewm you can even erase the contents of the window after restart. i3 also ignores `_NET_WM_STATE_ABOVE`, but the window is still visible (but layered on the bottom).

I'm not getting enlightened by the [WM spec section](https://specifications.freedesktop.org/wm-spec/wm-spec-1.5.html#idm140200472615568) either and so I don't know if I actually have to fix it in dunst or say, it's awesome's/i3's issue.

**Comment by bebehei** [comment] 2018-04-25 15:12
Well, it's not i3's issue. See https://github.com/i3/i3/issues/3265#issuecomment-384314904 I now understand i3's behavior, which was quite weird for me.

It finally think this is actually a bug in awesomewm.

**Comment by psychon** [comment] 2018-04-26 15:10
The only call to `XCreateWindow` "in here" that I found sets [OverrideRedirect to true](https://github.com/dunst-project/dunst/blob/f80e6fc5793ee21bc8f97dc904c1bbe610a64692/src/x11/x.c#L1144). Such windows are not managed by the WM and so setting `_NET_WM_STATE_ABOVE` has no effect.

This issue is also not specific to restarting awesome:
From the X11 protocol reference, new windows are on top of the stacking order (docs for `CreateWindow`):

> The window is placed on top in the stacking order with respect to siblings.

https://www.x.org/releases/X11R7.5/doc/x11proto/proto.html (sorry, you have to scroll quite a bit to find the paragraph)

Thus, any window that is created after dunst created its window will end up being above it.

If you want to waste CPU time, I would suggest setting a timer and raising your window e.g. every five seconds. If you want to spend a bit more coder timer, select `SubstructureNotify` on the root window and raise your window(s) whenever you get a `CreateNotify` event.

**Comment by bebehei** [comment] 2018-04-26 15:52
@psychon Thanks for enlighting us. Do I read your post right, that `_NET_WM_STATE_ABOVE` is actually [useless and void in our code](https://github.com/dunst-project/dunst/blob/f80e6fc5793ee21bc8f97dc904c1bbe610a64692/src/x11/x.c#L1117-L1124) and we actually should remove it?

> If you want to spend a bit more coder timer, select SubstructureNotify on the root window and raise your window(s) whenever you get a CreateNotify event.

@tsipinakis I think that could be even the easiest and cleanest solution to solve this bug here and even https://github.com/dunst-project/dunst/pull/496#issuecomment-381760930 which was my initial researcher bug. Then you can call `x_win_show` all the time you like, still have the `visible` field removed and as I assume it's just a few lines in code.

@tsipinakis Would you mind implementing the solution in #496 ?

**Comment by psychon** [comment] 2018-04-27 08:51
> Do I read your post right, that _NET_WM_STATE_ABOVE is actually useless and void in our code and we actually should remove it?

Well... I do not know. If you want me to guess: Yes. However, I wouldn't bet that there is nothing out there that actually looks at that property (but I do not really know what piece of software this would be; However since this is X11, something surely does).

>  I think that could be even the easiest and cleanest solution to solve this bug here and even #496 (comment) which was my initial researcher bug. 

Well, no, my suggestion would actually make dunst show consistently above the lock screen. Once the lock screen is opened, dunst would raise its own window above it. If I remember correctly, xscreensaver raises its own window to the top every `$X` seconds, but I'd be surprised if e.g. i3lock were to do the same.

Oh, wait. No, my suggestion would not make dunst show consistently above the lock screen. Instead, there is the possibility for a race. i3lock creates its window and then raises it to the top. If dunst manages to raise its own window between i3lock creating and raising its window, i3lock ends up on top. Otherwise, dunst ends up on top.
https://github.com/i3/i3lock/blob/ae72b675ca4f104fc210e5ad476a8b91acf6beb3/xcb.c#L129-L160

(However, since xcb caches requests and does not actually send out things immediately, this race is highly unlikely and I would expect dunst to end up consistently above the lock screen)

**Comment by bebehei** [comment] 2018-04-30 10:36
> verify that it works correctly?

Yes, I can verify it now for awesomewm. @tsipinakis awesome! Testing it with i3lock still stands out, but this will be part of review in #496.

**Closed as completed** 2018-05-14 09:22 UTC
Labels: Bug
