### ISSUE TITLE
When truncating multiples of the same message with icons, dunst segfaults

### ISSUE THREAD

**Issue by SethBarberee** [dunst-project/dunst#325] opened 2017-05-25 00:44 UTC
When there are multiple notifications (with icons) that say the same thing, dunst truncates and has an error:
```
(110) Unable to run script : No such file or directory
(110) Unable to run script : No such file or directory
Could not load icon: ''
Could not load icon: ''
*** Error in dunst: free(): invalid next size (fast): 0x00000000013cb0a0 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x722ab)[0x7f566388e2ab]
/usr/lib/libc.so.6(+0x7890e)[0x7f566389490e]
/usr/lib/libc.so.6(+0x7911e)[0x7f566389511e]
dunst[0x404cbd]
dunst[0x404e90]
dunst[0x40642f]
dunst[0x406b28]
/usr/lib/libgio-2.0.so.0(+0xbc7ac)[0x7f5664d8b7ac]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x15a)[0x7f566435a66a]
/usr/lib/libglib-2.0.so.0(+0x4aa20)[0x7f566435aa20]
/usr/lib/libglib-2.0.so.0(g_main_loop_run+0xc2)[0x7f566435ad42]
dunst[0x4041b0]
/usr/lib/libc.so.6(__libc_start_main+0xf1)[0x7f566383c511]
dunst[0x4041fe]
======= Memory map: ========
00400000-0040e000 r-xp 00000000 08:02 4221292                            /usr/bin/dunst
0060d000-0060e000 r--p 0000d000 08:02 4221292                            /usr/bin/dunst
0060e000-0060f000 rw-p 0000e000 08:02 4221292                            /usr/bin/dunst
013ba000-0154f000 rw-p 00000000 00:00 0                                  [heap]
7f5648000000-7f5648022000 rw-p 00000000 00:00 0 
7f5648022000-7f564c000000 ---p 00000000 00:00 0 
7f5650000000-7f5650022000 rw-p 00000000 00:00 0 
7f5650022000-7f5654000000 ---p 00000000 00:00 0 
7f5654000000-7f5654022000 rw-p 00000000 00:00 0 
7f5654022000-7f5658000000 ---p 00000000 00:00 0 
7f5658000000-7f5658021000 rw-p 00000000 00:00 0 
7f5658021000-7f565c000000 ---p 00000000 00:00 0 
7f565c8b6000-7f565c8cc000 r-xp 00000000 08:02 4197922                    /usr/lib/libgcc_s.so.1
7f565c8cc000-7f565cacb000 ---p 00016000 08:02 4197922                    /usr/lib/libgcc_s.so.1
7f565cacb000-7f565cacc000 r--p 00015000 08:02 4197922                    /usr/lib/libgcc_s.so.1
7f565cacc000-7f565cacd000 rw-p 00016000 08:02 4197922                    /usr/lib/libgcc_s.so.1
7f565cacd000-7f565cccd000 rw-s 00000000 00:05 16809989                   /SYSV00000000 (deleted)
7f565cdfe000-7f565ce3f000 rw-p 00000000 00:00 0 
7f565ce3f000-7f565ce55000 r--p 00000000 08:02 4858579                    /usr/share/fonts/TTF/Overpass-Regular.ttf
7f565ce55000-7f565ce6b000 r--p 00000000 08:02 4858577                    /usr/share/fonts/TTF/Overpass-Bold.ttf
7f565ce6b000-7f565cead000 r--s 00000000 08:02 11275311                   /var/cache/fontconfig/923e285e415b1073c8df160bee08820f-le64.cache-7
7f565cead000-7f565cec7000 r--s 00000000 08:02 11274596                   /var/cache/fontconfig/8d4af663993b81a124ee82e610bb31f9-le64.cache-7
7f565cec7000-7f565cec8000 ---p 00000000 00:00 0 
7f565cec8000-7f565d6c8000 rw-p 00000000 00:00 0 
7f565d6c8000-7f565d6c9000 ---p 00000000 00:00 0 
7f565d6c9000-7f565dec9000 rw-p 00000000 00:00 0 
7f565dec9000-7f565deca000 ---p 00000000 00:00 0 
7f565deca000-7f565e6ca000 rw-p 00000000 00:00 0 
7f565e6ca000-7f565e6cb000 ---p 00000000 00:00 0 
7f565e6cb000-7f565eecb000 rw-p 00000000 00:00 0 
7f565eecb000-7f565eef5000 r-xp 00000000 08:02 4220267                    /usr/lib/libgraphite2.so.3.0.1
7f565eef5000-7f565f0f4000 ---p 0002a000 08:02 4220267                    /usr/lib/libgraphite2.so.3.0.1
7f565f0f4000-7f565f0f6000 r--p 00029000 08:02 4220267                    /usr/lib/libgraphite2.so.3.0.1
7f565f0f6000-7f565f0f7000 rw-p 0002b000 08:02 4220267                    /usr/lib/libgraphite2.so.3.0.1
7f565f0f7000-7f565f107000 r-xp 00000000 08:02 4225225                    /usr/lib/libGLX.so.0.0.0
7f565f107000-7f565f307000 ---p 00010000 08:02 4225225                    /usr/lib/libGLX.so.0.0.0
7f565f307000-7f565f308000 r--p 00010000 08:02 4225225                    /usr/lib/libGLX.so.0.0.0
7f565f308000-7f565f309000 rw-p 00011000 08:02 4225225                    /usr/lib/libGLX.so.0.0.0
7f565f309000-7f565f329000 rw-p 00000000 00:00 0 
7f565f329000-7f565f397000 r-xp 00000000 08:02 4225219                    /usr/lib/libGLdispatch.so.0.0.0
7f565f397000-7f565f596000 ---p 0006e000 08:02 4225219                    /usr/lib/libGLdispatch.so.0.0.0
7f565f596000-7f565f5be000 r--p 0006d000 08:02 4225219                    /usr/lib/libGLdispatch.so.0.0.0
7f565f5be000-7f565f5bf000 rw-p 00095000 08:02 4225219                    /usr/lib/libGLdispatch.so.0.0.0
7f565f5bf000-7f565f5df000 rw-p 00000000 00:00 0 
7f565f5df000-7f565f5e6000 r-xp 00000000 08:02 4200819                    /usr/lib/libdatrie.so.1.3.3
7f565f5e6000-7f565f7e5000 ---p 00007000 08:02 4200819                    /usr/lib/libdatrie.so.1.3.3
7f565f7e5000-7f565f7e6000 r--p 00006000 08:02 4200819                    /usr/lib/libdatrie.so.1.3.3
7f565f7e6000-7f565f7e7000 rw-p 00007000 08:02 4200819                    /usr/lib/libdatrie.so.1.3.3
7f565f7e7000-7f565f7f6000 r-xp 00000000 08:02 4200820                    /usr/lib/libbz2.so.1.0.6
7f565f7f6000-7f565f9f5000 ---p 0000f000 08:02 4200820                    /usr/lib/libbz2.so.1.0.6
7f565f9f5000-7f565f9f6000 r--p 0000e000 08:02 4200820                    /usr/lib/libbz2.so.1.0.6
7f565f9f6000-7f565f9f7000 rw-p 0000f000 08:02 4200820                    /usr/lib/libbz2.so.1.0.6
7f565f9f7000-7f565fa1e000 r-xp 00000000 08:02 4204844                    /usr/lib/libexpat.so.1.6.2
7f565fa1e000-7f565fc1e000 ---p 00027000 08:02 4204844                    /usr/lib/libexpat.so.1.6.2
7f565fc1e000-7f565fc20000 r--p 00027000 08:02 4204844                    /usr/lib/libexpat.so.1.6.2
7f565fc20000-7f565fc21000 rw-p 00029000 08:02 4204844                    /usr/lib/libexpat.so.1.6.2
7f565fc21000-7f565fcb3000 r-xp 00000000 08:02 4204974                    /usr/lib/libharfbuzz.so.0.10400.6
7f565fcb3000-7f565feb2000 ---p 00092000 08:02 4204974                    /usr/lib/libharfbuzz.so.0.10400.6
7f565feb2000-7f565feb4000 r--p 00091000 08:02 4204974                    /usr/lib/libharfbuzz.so.0.10400.6
7f565feb4000-7f565feb5000 rw-p 00093000 08:02 4204974                    /usr/lib/libharfbuzz.so.0.10400.6
7f565feb5000-7f565feb9000 r-xp 00000000 08:02 4214659                    /usr/lib/libuuid.so.1.3.0
7f565feb9000-7f56600b8000 ---p 00004000 08:02 4214659                    /usr/lib/libuuid.so.1.3.0
7f56600b8000-7f56600b9000 r--p 00003000 08:02 4214659                    /usr/lib/libuuid.so.1.3.0
7f56600b9000-7f56600ba000 rw-p 00004000 08:02 4214659                    /usr/lib/libuuid.so.1.3.0
7f56600ba000-7f56600fb000 r-xp 00000000 08:02 4214660                    /usr/lib/libblkid.so.1.1.0
7f56600fb000-7f56602fa000 ---p 00041000 08:02 4214660                    /usr/lib/libblkid.so.1.1.0
7f56602fa000-7f56602fe000 r--p 00040000 08:02 4214660                    /usr/lib/libblkid.so.1.1.0
7f56602fe000-7f56602ff000 rw-p 00044000 08:02 4214660                    /usr/lib/libblkid.so.1.1.0
7f56602ff000-7f5660300000 rw-p 00000000 00:00 0 
7f5660300000-7f5660305000 r-xp 00000000 08:02 4216501                    /usr/lib/libXdmcp.so.6.0.0
7f5660305000-7f5660504000 ---p 00005000 08:02 4216501                    /usr/lib/libXdmcp.so.6.0.0
7f5660504000-7f5660505000 r--p 00004000 08:02 4216501                    /usr/lib/libXdmcp.so.6.0.0
7f5660505000-7f5660506000 rw-p 00005000 08:02 4216501                    /usr/lib/libXdmcp.so.6.0.0
7f5660506000-7f5660508000 r-xp 00000000 08:02 4216505                    /usr/lib/libXau.so.6.0.0
7f5660508000-7f5660708000 ---p 00002000 08:02 4216505                    /usr/lib/libXau.so.6.0.0
7f5660708000-7f5660709000 r--p 00002000 08:02 4216505                    /usr/lib/libXau.so.6.0.0
7f5660709000-7f566070a000 rw-p 00003000 08:02 4216505                    /usr/lib/libXau.so.6.0.0
7f566070a000-7f5660711000 r-xp 00000000 08:02 4196371                    /usr/lib/librt-2.25.so
7f5660711000-7f5660910000 ---p 00007000 08:02 4196371                    /usr/lib/librt-2.25.so
7f5660910000-7f5660911000 r--p 00006000 08:02 4196371                    /usr/lib/librt-2.25.so
7f5660911000-7f5660912000 rw-p 00007000 08:02 4196371                    /usr/lib/librt-2.25.so
7f5660912000-7f5660982000 r-xp 00000000 08:02 4225226                    /usr/lib/libGL.so.1.0.0
7f5660982000-7f5660b81000 ---p 00070000 08:02 4225226                    /usr/lib/libGL.so.1.0.0
7f5660b81000-7f5660b9b000 r--p 0006f000 08:02 4225226                    /usr/lib/libGL.so.1.0.0
7f5660b9b000-7f5660b9c000 rw-p 00089000 08:02 4225226                    /usr/lib/libGL.so.1.0.0
7f5660b9c000-7f5660b9d000 rw-p 00000000 00:00 0 
7f5660b9d000-7f5660ba6000 r-xp 00000000 08:02 4220787                    /usr/lib/libXrender.so.1.3.0
7f5660ba6000-7f5660da6000 ---p 00009000 08:02 4220787                    /usr/lib/libXrender.so.1.3.0
7f5660da6000-7f5660da7000 r--p 00009000 08:02 4220787                    /usr/lib/libXrender.so.1.3.0
7f5660da7000-7f5660da8000 rw-p 0000a000 08:02 4220787                    /usr/lib/libXrender.so.1.3.0
7f5660da8000-7f5660db4000 r-xp 00000000 08:02 4216576                    /usr/lib/libxcb-render.so.0.0.0
7f5660db4000-7f5660fb4000 ---p 0000c000 08:02 4216576                    /usr/lib/libxcb-render.so.0.0.0
7f5660fb4000-7f5660fb5000 r--p 0000c000 08:02 4216576                    /usr/lib/libxcb-render.so.0.0.0
7f5660fb5000-7f5660fb6000 rw-p 0000d000 08:02 4216576                    /usr/lib/libxcb-render.so.0.0.0
7f5660fb6000-7f5660fb8000 r-xp 00000000 08:02 4216580                    /usr/lib/libxcb-shm.so.0.0.0
7f5660fb8000-7f56611b8000 ---p 00002000 08:02 4216580                    /usr/lib/libxcb-shm.so.0.0.0
7f56611b8000-7f56611b9000 r--p 00002000 08:02 4216580                    /usr/lib/libxcb-shm.so.0.0.0
7f56611b9000-7f56611ba000 rw-p 00003000 08:02 4216580                    /usr/lib/libxcb-shm.so.0.0.0
7f56611ba000-7f56611ef000 r-xp 00000000 08:02 4220251                    /usr/lib/libpng16.so.16.29.0
7f56611ef000-7f56613ee000 ---p 00035000 08:02 4220251                    /usr/lib/libpng16.so.16.29.0
7f56613ee000-7f56613ef000 r--p 00034000 08:02 4220251                    /usr/lib/libpng16.so.16.29.0
7f56613ef000-7f56613f0000 rw-p 00035000 08:02 4220251                    /usr/lib/libpng16.so.16.29.0
7f56613f0000-7f5661402000 r-xp 00000000 08:02 4225224                    /usr/lib/libEGL.so.1.0.0
7f5661402000-7f5661601000 ---p 00012000 08:02 4225224                    /usr/lib/libEGL.so.1.0.0
7f5661601000-7f5661602000 r--p 00011000 08:02 4225224                    /usr/lib/libEGL.so.1.0.0
7f5661602000-7f5661603000 rw-p 00012000 08:02 4225224                    /usr/lib/libEGL.so.1.0.0
7f5661603000-7f56616a2000 r-xp 00000000 08:02 4220297                    /usr/lib/libpixman-1.so.0.34.0
7f56616a2000-7f56618a2000 ---p 0009f000 08:02 4220297                    /usr/lib/libpixman-1.so.0.34.0
7f56618a2000-7f56618aa000 r--p 0009f000 08:02 4220297                    /usr/lib/libpixman-1.so.0.34.0
7f56618aa000-7f56618ab000 rw-p 000a7000 08:02 4220297                    /usr/lib/libpixman-1.so.0.34.0
7f56618ab000-7f566191d000 r-xp 00000000 08:02 4207467                    /usr/lib/libpcre.so.1.2.8
7f566191d000-7f5661b1c000 ---p 00072000 08:02 4207467                    /usr/lib/libpcre.so.1.2.8
7f5661b1c000-7f5661b1d000 r--p 00071000 08:02 4207467                    /usr/lib/libpcre.so.1.2.8
7f5661b1d000-7f5661b1e000 rw-p 00072000 08:02 4207467                    /usr/lib/libpcre.so.1.2.8
7f5661b1e000-7f5661b25000 r-xp 00000000 08:02 4207596                    /usr/lib/libffi.so.6.0.4
7f5661b25000-7f5661d25000 ---p 00007000 08:02 4207596                    /usr/lib/libffi.so.6.0.4
7f5661d25000-7f5661d26000 r--p 00007000 08:02 4207596                    /usr/lib/libffi.so.6.0.4
7f5661d26000-7f5661d27000 rw-p 00008000 08:02 4207596                    /usr/lib/libffi.so.6.0.4
7f5661d27000-7f5661d2f000 r-xp 00000000 08:02 4221241                    /usr/lib/libthai.so.0.3.0
7f5661d2f000-7f5661f2f000 ---p 00008000 08:02 4221241                    /usr/lib/libthai.so.0.3.0
7f5661f2f000-7f5661f30000 r--p 00008000 08:02 4221241                    /usr/lib/libthai.so.0.3.0
7f5661f30000-7f5661f31000 rw-p 00009000 08:02 4221241                    /usr/lib/libthai.so.0.3.0
7f5661f31000-7f5661feb000 r-xp 00000000 08:02 4220281                    /usr/lib/libfreetype.so.6.13.0
7f5661feb000-7f56621eb000 ---p 000ba000 08:02 4220281                    /usr/lib/libfreetype.so.6.13.0
7f56621eb000-7f56621f1000 r--p 000ba000 08:02 4220281                    /usr/lib/libfreetype.so.6.13.0
7f56621f1000-7f56621f2000 rw-p 000c0000 08:02 4220281                    /usr/lib/libfreetype.so.6.13.0
7f56621f2000-7f5662304000 r-xp 00000000 08:02 4196374                    /usr/lib/libm-2.25.so
7f5662304000-7f5662503000 ---p 00112000 08:02 4196374                    /usr/lib/libm-2.25.so
7f5662503000-7f5662504000 r--p 00111000 08:02 4196374                    /usr/lib/libm-2.25.so
7f5662504000-7f5662505000 rw-p 00112000 08:02 4196374                    /usr/lib/libm-2.25.so
7f5662505000-7f5662543000 r-xp 00000000 08:02 4220577                    /usr/lib/libfontconfig.so.1.9.2
7f5662543000-7f5662742000 ---p 0003e000 08:02 4220577                    /usr/lib/libfontconfig.so.1.9.2
7f5662742000-7f5662744000 r--p 0003d000 08:02 4220577                    /usr/lib/libfontconfig.so.1.9.2
7f5662744000-7f5662749000 rw-p 0003f000 08:02 4220577                    /usr/lib/libfontconfig.so.1.9.2
7f5662749000-7f566275d000 r-xp 00000000 08:02 4221021                    /usr/lib/libpangoft2-1.0.so.0.4000.5
7f566275d000-7f566295c000 ---p 00014000 08:02 4221021                    /usr/lib/libpangoft2-1.0.so.0.4000.5
7f566295c000-7f566295d000 r--p 00013000 08:02 4221021                    /usr/lib/libpangoft2-1.0.so.0.4000.5
7f566295d000-7f566295e000 rw-p 00014000 08:02 4221021                    /usr/lib/libpangoft2-1.0.so.0.4000.5
7f566295e000-7f56629a8000 r-xp 00000000 08:02 4226375                    /usr/lib/libmount.so.1.1.0
7f56629a8000-7f5662ba8000 ---p 0004a000 08:02 4226375                    /usr/lib/libmount.so.1.1.0
7f5662ba8000-7f5662ba9000 r--p 0004a000 08:02 4226375                    /usr/lib/libmount.so.1.1.0
7f5662ba9000-7f5662baa000 rw-p 0004b000 08:02 4226375                    /usr/lib/libmount.so.1.1.0
7f5662baa000-7f5662bac000 rw-p 00000000 00:00 0 
7f5662bac000-7f5662bbf000 r-xp 00000000 08:02 4196372                    /usr/lib/libresolv-2.25.so
7f5662bbf000-7f5662dbe000 ---p 00013000 08:02 4196372                    /usr/lib/libresolv-2.25.so
7f5662dbe000-7f5662dbf000 r--p 00012000 08:02 4196372                    /usr/lib/libresolv-2.25.so
7f5662dbf000-7f5662dc0000 rw-p 00013000 08:02 4196372                    /usr/lib/libresolv-2.25.so
7f5662dc0000-7f5662dc2000 rw-p 00000000 00:00 0 
7f5662dc2000-7f5662dd8000 r-xp 00000000 08:02 4204924                    /usr/lib/libz.so.1.2.11
7f5662dd8000-7f5662fd7000 ---p 00016000 08:02 4204924                    /usr/lib/libz.so.1.2.11
7f5662fd7000-7f5662fd8000 r--p 00015000 08:02 4204924                    /usr/lib/libz.so.1.2.11
7f5662fd8000-7f5662fd9000 rw-p 00016000 08:02 4204924                    /usr/lib/libz.so.1.2.11
7f5662fd9000-7f5662fdc000 r-xp 00000000 08:02 4207676                    /usr/lib/libgmodule-2.0.so.0.5200.1
7f5662fdc000-7f56631db000 ---p 00003000 08:02 4207676                    /usr/lib/libgmodule-2.0.so.0.5200.1
7f56631db000-7f56631dc000 r--p 00002000 08:02 4207676                    /usr/lib/libgmodule-2.0.so.0.5200.1
7f56631dc000-7f56631dd000 rw-p 00003000 08:02 4207676                    /usr/lib/libgmodule-2.0.so.0.5200.1
7f56631dd000-7f56631e0000 r-xp 00000000 08:02 4196375                    /usr/lib/libdl-2.25.so
7f56631e0000-7f56633df000 ---p 00003000 08:02 4196375                    /usr/lib/libdl-2.25.so
7f56633df000-7f56633e0000 r--p 00002000 08:02 4196375                    /usr/lib/libdl-2.25.so
7f56633e0000-7f56633e1000 rw-p 00003000 08:02 4196375                    /usr/lib/libdl-2.25.so
7f56633e1000-7f5663409000 r-xp 00000000 08:02 4216566                    /usr/lib/libxcb.so.1.1.0
7f5663409000-7f5663608000 ---p 00028000 08:02 4216566                    /usr/lib/libxcb.so.1.1.0
7f5663608000-7f5663609000 r--p 00027000 08:02 4216566                    /usr/lib/libxcb.so.1.1.0
7f5663609000-7f566360a000 rw-p 00028000 08:02 4216566                    /usr/lib/libxcb.so.1.1.0
7f566360a000-7f566361b000 r-xp 00000000 08:02 4219746                    /usr/lib/libXext.so.6.4.0
7f566361b000-7f566381a000 ---p 00011000 08:02 4219746                    /usr/lib/libXext.so.6.4.0
7f566381a000-7f566381b000 r--p 00010000 08:02 4219746                    /usr/lib/libXext.so.6.4.0
7f566381b000-7f566381c000 rw-p 00011000 08:02 4219746                    /usr/lib/libXext.so.6.4.0
7f566381c000-7f56639b7000 r-xp 00000000 08:02 4196497                    /usr/lib/libc-2.25.so
7f56639b7000-7f5663bb6000 ---p 0019b000 08:02 4196497                    /usr/lib/libc-2.25.so
7f5663bb6000-7f5663bba000 r--p 0019a000 08:02 4196497                    /usr/lib/libc-2.25.so
7f5663bba000-7f5663bbc000 rw-p 0019e000 08:02 4196497                    /usr/lib/libc-2.25.so
7f5663bbc000-7f5663bc0000 rw-p 00000000 00:00 0 
7f5663bc0000-7f5663bd9000 r-xp 00000000 08:02 4196516                    /usr/lib/libpthread-2.25.so
7f5663bd9000-7f5663dd8000 ---p 00019000 08:02 4196516                    /usr/lib/libpthread-2.25.so
7f5663dd8000-7f5663dd9000 r--p 00018000 08:02 4196516                    /usr/lib/libpthread-2.25.so
7f5663dd9000-7f5663dda000 rw-p 00019000 08:02 4196516                    /usr/lib/libpthread-2.25.so
7f5663dda000-7f5663dde000 rw-p 00000000 00:00 0 
7f5663dde000-7f5663de1000 r-xp 00000000 08:02 4221223                    /usr/lib/libxdg-basedir.so.1.2.0
7f5663de1000-7f5663fe0000 ---p 00003000 08:02 4221223                    /usr/lib/libxdg-basedir.so.1.2.0
7f5663fe0000-7f5663fe1000 r--p 00002000 08:02 4221223                    /usr/lib/libxdg-basedir.so.1.2.0
7f5663fe1000-7f5663fe2000 rw-p 00003000 08:02 4221223                    /usr/lib/libxdg-basedir.so.1.2.0
7f5663fe2000-7f566410b000 r-xp 00000000 08:02 4221247                    /usr/lib/libcairo.so.2.11400.8
7f566410b000-7f566430a000 ---p 00129000 08:02 4221247                    /usr/lib/libcairo.so.2.11400.8
7f566430a000-7f566430d000 r--p 00128000 08:02 4221247                    /usr/lib/libcairo.so.2.11400.8
7f566430d000-7f566430f000 rw-p 0012b000 08:02 4221247                    /usr/lib/libcairo.so.2.11400.8
7f566430f000-7f5664310000 rw-p 00000000 00:00 0 
7f5664310000-7f5664421000 r-xp 00000000 08:02 4207675                    /usr/lib/libglib-2.0.so.0.5200.1
7f5664421000-7f5664621000 ---p 00111000 08:02 4207675                    /usr/lib/libglib-2.0.so.0.5200.1
7f5664621000-7f5664622000 r--p 00111000 08:02 4207675                    /usr/lib/libglib-2.0.so.0.5200.1
7f5664622000-7f5664623000 rw-p 00112000 08:02 4207675                    /usr/lib/libglib-2.0.so.0.5200.1
7f5664623000-7f5664624000 rw-p 00000000 00:00 0 
7f5664624000-7f5664675000 r-xp 00000000 08:02 4207678                    /usr/lib/libgobject-2.0.so.0.5200.1
7f5664675000-7f5664874000 ---p 00051000 08:02 4207678                    /usr/lib/libgobject-2.0.so.0.5200.1
7f5664874000-7f5664875000 r--p 00050000 08:02 4207678                    /usr/lib/libgobject-2.0.so.0.5200.1
7f5664875000-7f5664876000 rw-p 00051000 08:02 4207678                    /usr/lib/libgobject-2.0.so.0.5200.1
7f5664876000-7f56648bf000 r-xp 00000000 08:02 4221020                    /usr/lib/libpango-1.0.so.0.4000.5
7f56648bf000-7f5664abf000 ---p 00049000 08:02 4221020                    /usr/lib/libpango-1.0.so.0.4000.5
7f5664abf000-7f5664ac1000 r--p 00049000 08:02 4221020                    /usr/lib/libpango-1.0.so.0.4000.5
7f5664ac1000-7f5664ac2000 rw-p 0004b000 08:02 4221020                    /usr/lib/libpango-1.0.so.0.4000.5
7f5664ac2000-7f5664ace000 r-xp 00000000 08:02 4221023                    /usr/lib/libpangocairo-1.0.so.0.4000.5
7f5664ace000-7f5664ccd000 ---p 0000c000 08:02 4221023                    /usr/lib/libpangocairo-1.0.so.0.4000.5
7f5664ccd000-7f5664cce000 r--p 0000b000 08:02 4221023                    /usr/lib/libpangocairo-1.0.so.0.4000.5
7f5664cce000-7f5664ccf000 rw-p 0000c000 08:02 4221023                    /usr/lib/libpangocairo-1.0.so.0.4000.5
7f5664ccf000-7f5664e5b000 r-xp 00000000 08:02 4207679                    /usr/lib/libgio-2.0.so.0.5200.1
7f5664e5b000-7f566505b000 ---p 0018c000 08:02 4207679                    /usr/lib/libgio-2.0.so.0.5200.1
7f566505b000-7f5665060000 r--p 0018c000 08:02 4207679                    /usr/lib/libgio-2.0.so.0.5200.1
7f5665060000-7f5665062000 rw-p 00191000 08:02 4207679                    /usr/lib/libgio-2.0.so.0.5200.1
7f5665062000-7f5665064000 rw-p 00000000 00:00 0 
7f5665064000-7f566519d000 r-xp 00000000 08:02 4219678                    /usr/lib/libX11.so.6.3.0
7f566519d000-7f566539d000 ---p 00139000 08:02 4219678                    /usr/lib/libX11.so.6.3.0
7f566539d000-7f566539e000 r--p 00139000 08:02 4219678                    /usr/lib/libX11.so.6.3.0
7f566539e000-7f56653a3000 rw-p 0013a000 08:02 4219678                    /usr/lib/libX11.so.6.3.0
7f56653a3000-7f56653a5000 r-xp 00000000 08:02 4220814                    /usr/lib/libXinerama.so.1.0.0
7f56653a5000-7f56655a4000 ---p 00002000 08:02 4220814                    /usr/lib/libXinerama.so.1.0.0
7f56655a4000-7f56655a5000 r--p 00001000 08:02 4220814                    /usr/lib/libXinerama.so.1.0.0
7f56655a5000-7f56655a6000 rw-p 00002000 08:02 4220814                    /usr/lib/libXinerama.so.1.0.0
7f56655a6000-7f56655a8000 r-xp 00000000 08:02 4221208                    /usr/lib/libXss.so.1.0.0
7f56655a8000-7f56657a8000 ---p 00002000 08:02 4221208                    /usr/lib/libXss.so.1.0.0
7f56657a8000-7f56657a9000 r--p 00002000 08:02 4221208                    /usr/lib/libXss.so.1.0.0
7f56657a9000-7f56657aa000 rw-p 00003000 08:02 4221208                    /usr/lib/libXss.so.1.0.0
7f56657aa000-7f56657cd000 r-xp 00000000 08:02 4196498                    /usr/lib/ld-2.25.so
7f56657d9000-7f56657fe000 r--s 00000000 08:02 11275011                   /var/cache/fontconfig/f6b893a7224233d96cb72fd88691c0b4-le64.cache-7
7f56657fe000-7f5665996000 r--p 00000000 08:02 4225205                    /usr/lib/locale/locale-archive
7f5665996000-7f56659ac000 rw-p 00000000 00:00 0 
7f56659b8000-7f56659b9000 rw-p 00000000 00:00 0 
7f56659b9000-7f56659c2000 r--s 00000000 08:02 11273534                   /var/cache/fontconfig/f349e9996a5320f6dd491cedd2b1f964-le64.cache-7
7f56659c2000-7f56659cc000 r--s 00000000 08:03 1317043                    /home/seth/.cache/fontconfig/ce0247f155206aba44d2b12d7516b641-le64.cache-7
7f56659cc000-7f56659cd000 r--p 00022000 08:02 4196498                    /usr/lib/ld-2.25.so
7f56659cd000-7f56659ce000 rw-p 00023000 08:02 4196498                    /usr/lib/ld-2.25.so
7f56659ce000-7f56659cf000 rw-p 00000000 00:00 0 
7ffc4e736000-7ffc4e757000 rw-p 00000000 00:00 0                          [stack]
7ffc4e79d000-7ffc4e79f000 r--p 00000000 00:00 0                          [vvar]
7ffc4e79f000-7ffc4e7a1000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)
```

[dunst config](https://gist.github.com/SethBarberee/7a3226651c25469f0facda7a01d13052)

**Comment by tsipinakis** [comment] 2017-05-25 07:32
Please use [fenced code blocks](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) to post error logs to preserve formatting

The config file you provided appears to have a few sections dusplicated which prevents dunst from loading it. Perhaps it was pasted incorrectly?
Can you provide a few test cases with notifications that cause the crash?

**Comment by SethBarberee** [comment] 2017-05-25 14:21
Fixed both the log and the config file. I had a copying error in neovim to my clipboard. 

***Test Case***
- Run dunst from terminal (did this to show output)
- Send a notification with an icon
- Send the same notification again (with an icon)
- When it truncates to show multiple of the same message, dunst segfaults

**Comment by tsipinakis** [comment] 2017-05-25 16:08
This is probably a duplicate of #281 which has already been fixed in master. Can you compile the latest version and see if the problem is still there?

**Closed** 2017-05-31 03:26 UTC
Labels: Bug, unconfirmed
