### ISSUE TITLE
What's the deal with &?

### ISSUE THREAD

**Issue by catzybluphish** [dunst-project/dunst#572] opened 2018-12-02 09:32 UTC
When Dunst appears for Spotify to show the current song, artist, etc. if it contains a "&" in any of the text, it'll show the following error:
![2018-12-02-192412_960x530_scrot](https://user-images.githubusercontent.com/40843060/49337986-f9559500-f667-11e8-9d66-8c3ef848bbe3.png)
Not sure what it means and I've read the man page where it addresses it a bit.
How it affects the notification is that it removes all markup of the text. When I usually would have bold for the title and italics for artist, it'd change to basic formatting. What can I do to fix this?
[config](https://pastebin.com/ZtiHkVTa)

**Comment by tsipinakis** [comment] 2018-12-02 09:37
Duplicate of #546.

Try building from source, it should mostly work as intended now.

**Closed by tsipinakis** 2018-12-02 09:37 UTC
