### ISSUE TITLE
Feature Req; Transparency with separator?

### ISSUE THREAD

**Issue by ghost** [dunst-project/dunst#621] opened 2019-04-04 09:07 UTC
Is this a thing? Whenever I turn on the separator it seems to have a colour where as I'd rather for it to be see-through.

**Comment by tsipinakis** [comment] 2019-04-08 13:09
Mostly a duplicate of #289. There's been an attempt to add this with #344 but failed due to some implementation details that we couldn't work around.

Another idea would be to have a separate window for each notification to create the same effect but haven't looked into it that much.

**Comment by TRSx80** [comment] 2020-03-08 06:56
> a separate window for each notification

As a very new user, I was pretty surprised to learn that this was not the case.

I am still loving Dunst, and thank you for all your work. But that one little niggle is triggering my OCD. :smile: :smile: :smile: 

Cheers!

**Comment by bynect** [comment] 2024-02-21 13:40
I think this is resolved by #717

**Closed** 2024-03-05 10:18 UTC
Labels: Feature
