### ISSUE TITLE
Wayland support, e.g. for sway wm

### ISSUE THREAD

**Issue by onny** [dunst-project/dunst#264] opened 2016-06-16 14:56 UTC
I tried to run dunst with the i3-compatible wayland twm sway but it won't work yet. Is there any wayland support planed or has this to be done in sway itself?

Best regards,
Jonas

**Comment by aaronsnin** [comment] 2016-07-13 23:03
What issues were you running into? Are you not willing to use the xwayland module? I've run dunst on xwayland in sway with good results. Due to the relative inactivity on this project I wouldn't expect to see any of the major overhauls necessary to switch over to a pure-wayland implementation.

**Comment by hobarrera** [comment] 2017-05-01 19:18
I've tried using dunst under wayland/sway but:

* Positioning is off. Dunst is always on the upper left corner.
* Global hotkeys don't work, so I can't close notifications with them, etc.
* Clicking notifications clicks through to the window behind it.

**Comment by tjaartvdwalt** [comment] 2017-08-18 18:03
@hobarrera, I do not know if there is any progress on this?

My experience on positioning: I struggled to get dunst to show in the top right corner, and failed. Hower, after a reboot, dunst now does appear on the top right. I am not sure why...

On the notifications clicks, I think this may be a sway issue, because a similar thing happens with popup dialogs.

**Comment by tsipinakis** [comment] 2017-08-19 05:39
I am currently in the process of refactoring the drawing code and separating from X11 related code in the [refactor-drawing](https://github.com/dunst-project/dunst/tree/refactor-drawing) branch, once that's done it should be easy to add on other display servers such as wayland.

That being said, I'm not using wayland myself so if it is to be implemented someone should step up and make sure it works properly since I can't test it that well.

**Comment by akiva** [comment] 2018-01-10 00:03
Any updates on this issue? Perhaps Sway's in-progress migration from wlc to wlroots will be of help?

**Comment by bebehei** [comment] 2018-01-11 14:55
First, we have to refactor our X11/drawing code. The code has to get split and simplified. Then we can get on and make it compatible to wayland. The process will take some time.

**Comment by alex3kov** [comment] 2018-04-22 19:06
I would gladly test dunst under Sway. Subscribed to this issue, please post here once there is something to test.

**Comment by bebehei** [comment] 2018-04-23 09:46
> We have designed a protocol that would allow to show notifications.

@emersion Could you please elaborate this? I guess, your referenced protocol is not about freedesktop notifications sent via `DBus`.

The main problems using dunst via the x11 wayland compatibility layer is that `XCreateWindow` is created with `x=0,y=0` and then dunst moves the window via `XWinMove` to its actual position. And according to [those IRC logs](https://people.freedesktop.org/~cbrill/dri-log/index.php?channel=wayland&highlight_names=&date=2017-02-10), `XWinMove` isn't supported on XWayland.

I'm not sure what might help, but @tsipinakis and myself are very inexperienced in X11 programming. @emersion If you want to review our current code and our thinking model, that would be a good choice.

**Comment by emersion** [comment] 2018-04-23 09:54
>I guess, your referenced protocol is not about freedesktop notifications sent via DBus.

The protocol can be used to create native Wayland surfaces on top of other windows, on a screen corner. No Xwayland involved.

>The main problems using dunst via the x11 wayland compatibility layer is that XCreateWindow is created with x=0,y=0 and then dunst moves the window via XWinMove to its actual position. And according to those IRC logs, XWinMove isn't supported on XWayland.

I'm using Dunst on Xwayland with sway-1.0-alpha.1 right now, and notifications appear at the correct position, so I guess XWinMove works now. It requires the compositor to support it though.

>I'm not sure what might help, but @tsipinakis and myself are very inexperienced in X11 programming. @emersion If you want to review our current code and our thinking model, that would be a good choice.

I'm _not_ an experienced X11 dev, and I'm not really interested in making the X11 code nice. :)

Though, I'm interested in adding nice Wayland support, without Xwayland. Is that something you're interested in?

**Comment by tsipinakis** [comment] 2018-05-14 08:32
Sorry for the late reply to this one. The drawing refactor is pretty much ready to be merged.

> I'm interested in adding nice Wayland support, without Xwayland. Is that something you're interested in?

Definitely, this refactor was done with having support for multiple outputs in mind.

I have pushed my [proposal](https://github.com/dunst-project/dunst/commit/ad1b6ed9fa0a7b0599bf884b89d84c0d75048ab5) on how multiple outputs should work in the `refactor-outputs` branch (keep in mind this is completely unreviewed, would love @bebehei's opinion on this.). You can use it as a way to start testing out how well wayland works with dunst if you are still interested in implementing native support.

**Comment by emersion** [comment] 2018-05-14 08:37
Gah, I started looking at porting dunst a week ago and concluded it would be difficult, so I ended up starting a new project from scratch.

**Comment by emersion** [comment] 2018-05-15 14:32
Note that Wayland clients cannot set global keybindings.

**Comment by tsipinakis** [comment] 2018-05-15 14:35
We've been planning to migrate away for global keybindings ourselves (see #284 ) so that shouldn't be a problem in the long run. For now that does mean that history is not going to work that well though unfortunately.

**Comment by concatime** [comment] 2018-11-03 21:30
Any news on this thread?

**Comment by emersion** [comment] 2018-11-03 22:42
@concatime If you want a Dunst replacement for Sway, you can try https://github.com/emersion/mako

**Comment by tsipinakis** [comment] 2018-11-04 06:47
@concatime Since none of the current maintainers (me and @bebehei ) actively use wayland we are waiting for someone that does to step up and implement this properly.

If anyone wants to work on this feel free to ping me for guidance or for any questions.

**Comment by ubone** [comment] 2018-11-21 05:52
dunst works for weston, sway and wayfire [dunstrc](https://gist.github.com/ubone/e17d6be51d5c0cf36af0d364b3846511)

**Comment by ZakharEl** [comment] 2018-12-19 01:40
Tsipinakis' refactor-outputs branch works in sway with correct positioning of the notifications but the keybindings still don't work. Thanks for the hard work Tsipinakis.

**Comment by bebehei** [comment] 2018-12-19 01:54
@ZakharEl Nice to hear this. I'm working currently on a `dunstcmd` command client. I haven't implemented a replacement for the keybindings yet. But I'll finish this pretty soon and fire then a PR. So we'll have wayland support pretty soon.

It may not be native support yet, but at least it should work.

**Comment by ZakharEl** [comment] 2018-12-21 02:41
@bebehei whenever you got the dunstcmd with a manual I'll be willing to test it for you and report what features work. Thanks bebehei I appreciate all the work you software developers do and the linux community.

**Comment by ZakharEl** [comment] 2018-12-21 03:33
Did more testing with the refactor-outputs branch and transparency does not work in sway but it does not click through the notification box to any app behind it which is good.

**Comment by tsipinakis** [comment] 2020-05-21 12:56
Since `dunstctl` is now merged and dunst no longer depends on keyboard shortcuts for basic functionality, I thought I'd give wayland support a shot.

> If you want a Dunst replacement for Sway, you can try https://github.com/emersion/mako

Kudos to the mako devs, I used the mako output/buffer code as a base and ported it to the dunst api.

Currently it's pretty simplistic, doesn't support any mouse events and only anchors the window on the top right, but I'll try to have full support for it soon.

You can try it out on the [wayland branch](https://github.com/dunst-project/dunst/tree/wayland), if anyone is interested in either helping improve this or test it please do ping me here (PR's on the wayland branch welcome :) ).

A rough todo list:
- [ ] Fix existing leaks/properly deconstruct all objects
- [ ] Screen dimension detection support
- [ ] Geometry margin support
- [ ] Geometry anchor support (top-left, top-right etc)
- [ ] Mouse click event support
- [ ] Focus follow mode support (AFAIK, there's no way to tell keyboard/mouse focus apart in wayland, so these will probably behave identically)
- [ ] Idle detection support
- [ ] round corner support
- [ ] transparency support

**Comment by emersion** [comment] 2020-05-21 14:02
>Since dunstctl is now merged and dunst no longer depends on keyboard shortcuts for basic functionality, I thought I'd give wayland support a shot.

Nice!

>Screen dimension detection support

Wayland clients shouldn't try to detect the screen size. The layer-shell configure events should be enough.

>AFAIK, there's no way to tell keyboard/mouse focus apart in wayland, so these will probably behave identically

wl_pointer and wl_keyboard focus are separate, see each interface's enter/leave events.

>Fullscreen window detection support

Not possible with wayland, however letting uses pick the layer-shell layer should allow them to choose whether notifications show on top of fullscreen windows or under them.

**Comment by ZakharEl** [comment] 2020-05-23 04:06
Sweet are you meaning to say that the master branch of dunst from the dunst-project now have been merged with dunst-ctl? If so what commit and what version of dunst were they merged? I'll try testing it out on wayland but I not sure if sway would be the best wayland window manager to test it with.

**Comment by tsipinakis** [comment] 2020-05-23 08:46
It was merged with https://github.com/dunst-project/dunst/commit/fb2ffd425e2cfe42de0c633bcdf3a0203bfef90d. So just building from master also gets you dunstctl now.

**Comment by progandy** [comment] 2020-05-23 09:39
> > AFAIK, there's no way to tell keyboard/mouse focus apart in wayland, so these will probably behave identically
> 
> wl_pointer and wl_keyboard focus are separate, see each interface's enter/leave events.

As far as I know, an unfocused client cannot detect the currently active output, though. It could be done on sway with the sway IPC protocol. I'd suggest adding a dunstctl command to change the output, then a script like this can move the notification window:

```
old=""
while read change && read output ; do
  if [[ ! $output = $old ]]; then
    old=$output
    dunstctl set-output $output
  fi
done < <(swaymsg -t subscribe -m '[ "workspace" ]' | jq --unbuffered ".change,.current.output")
```

**Comment by emersion** [comment] 2020-05-23 09:52
To display a layer-shell surface on the active output, set the output argument to NULL when creating the layer surface.

**Comment by ZakharEl** [comment] 2020-05-26 07:19
The problem with sway for this test case is the use of xorg-server-xwayland for X11 support might just port the functionality without actually natively running it through wayland thus not actually serving as a native wayland test case. I think I'll test it without that optional dependency.  If anyone else has or is planning on testing it with sway I would probably advise against having that dependency while testing it or pick a different wayland window manager, desktop environment, etc. The idea is that any and all wayland window managers, etc used to test it avoid an x11 compatability layer to truely test wayland support.

**Comment by ZakharEl** [comment] 2020-05-26 07:22
also thanks progandy for the advice.

**Comment by WhyNotHugo** [comment] 2020-05-26 07:47
Would testing it with `unset DISPLAY` ensure that no xwayland functionality gets in the way of testing?

**Comment by tsipinakis** [comment] 2020-05-26 11:18
To be completely sure, unseting `$DISPLAY` would work. However, the `wayland` branch currently [forces the use of the wayland protocol](https://github.com/dunst-project/dunst/blob/b7fcc96089bf2842302564d11552672996be1f5f/src/output.c#L49) (read: X11 shouldn't work at all in that branch at the moment), so it shouldn't matter.

**Comment by fwSmit** [comment] 2020-11-24 14:15
Hi I've picked up the project of making dunst work on wayland. Here is what I've done.
I've fixed a bug in #779 where notifications were not disappearing on wayland, because dunst thought the user was idle.
The idle functionality is now turned off in wayland, because there is no way to detect if a user is idle in wayland, I think.
Because of this bugfix, dunst should work well on XWayland. I'm not aware of any issues with that currently.

On top of that, I've been working on native wayland support. There are still a few bugs, but I'm getting there.
You can look at #781 for a list of bugs that have to be fixed, but I've copied the todo from above as well.

Current progress:

    * [ ]  Fix existing leaks/properly deconstruct all objects

    * [x]  Screen dimension detection support (by using anchors)

    * [X]  Geometry margin support

    * [X]  Geometry anchor support (top-left, top-right etc)

    * [X]  Mouse click event support

    * [ ]  Focus follow mode support

    * [x]  Idle detection support (Not possible)

    * [x]  round corner support (mouse clicks are still detected in a square though)

    * [x]  transparency support (only when specifying with color alpha, not with the setting 'transparency')

    * [x]  **X11/Wayland auto detection**

    * [ ]  Fullscreen handling (requires changing how the settings work)

**Comment by progandy** [comment] 2020-11-24 19:48
Idle detection might be possible by reading the systemd-logindl IdleHInt for the session or the [idle-client protocol](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/8). For XWayland someone would have to teach it that or write some daemon to simulate user activity while wayland is not idle.

> Focus follow mode support

That is partially possible (comment from emersion):

> To display a layer-shell surface on the active output, set the output argument to NULL when creating the layer surface.

**Comment by fwSmit** [comment] 2020-11-25 21:37
> Idle detection might be possible by reading the systemd-logindl IdleHInt for the session or the [idle-client protocol](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/8). For XWayland someone would have to teach it that or write some daemon (or patch the compositor) to simulate user activity while wayland is not idle.

Thanks, I've implemented that protocol. It's not an official wayland protocol yet, but wlroots (and with it sway) supports it.


> To display a layer-shell surface on the active output, set the output argument to NULL when creating the layer surface.

Turns out we already did that due to a bug. I'm working on fixing that.

**Comment by fwSmit** [comment] 2020-11-28 15:23
I have one bug that I can't seem to fix, so maybe one of you can help.
When running #781 on sway I have an issue where the input region is only updated after moving the poiner.
So to reproduce this open two notifications:
```
notify-send "a notification that is longer than the one below it."
notify-send "short"
````
When clicking the long notification away and (without moving your pointer) you can click again to dismiss the short notification. Even when your pointer isn't on a notification anymore.

The layer_surface gets updated correctly after clicking away the notification and according to the docs, only input that's on the surface should be accepted. This might be a sway bug, but i wasn't able to test this on another window manager.
Mako avoids this bug by having only notifications of the same width.

**Comment by fwSmit** [comment] 2020-11-28 16:08
If anyone is able to test #781 on wayland, that would be very welcome (@alex3kov).

**Comment by Narrat** [comment] 2020-11-28 19:24
No real testing involved currently, but at least I have your wayland-2 branch running with the hikari compositor. Which means I cannot test idle behaviour, as it doesn't support idle-client (as far as I know).
So far it is working as `1.5.0` (but I cannot really tell if it uses the xwayland backend or running natively :D )

**Comment by fwSmit** [comment] 2020-11-28 20:06
Cool. On a wayland compositor it will default to wayland output. If you want to be entirely sure, you can `dunst -verbosity info` and it will tell you what output it's using.
I see that hikari is based on wlroots, which does support the idle protocol, so there is a good chance hikari will as well. Until a few commits ago it even crashed when there was no idle support, so depending on the version you used you would have probably noticed.
To test if a compositor supports a given protocol you can run `weston-info`, which will list all supported protocols.

**Comment by Narrat** [comment] 2020-11-28 20:52
Thank you for the infos regarding on how to get the information.
Yes, hikari is wlroots based. But for example the layer-shell support is a rather newish enhancement (came with 1.1.0) for this compositor, so I doubt a less needed protocol is already implemented/supported :D
One general note: `weston-info` has a deprecation warning. So everyone who stumbles upon this and their `weston`-package doesn't offer the binary anymore: `wayland-info` is the replacement (https://lists.freedesktop.org/archives/wayland-devel/2020-July/041520.html) (https://gitlab.freedesktop.org/ofourdan/wayland-info). Dunno if it will be shipped with the wayland package or stays standalone.

Running the dunst command at least offered the information what output is used. Looking good so far. The following line not so much. Dunno what is at fault.
```
~ $ dunst -verbosity info                                                        
INFO: Using Wayland output
zsh: segmentation fault (core dumped)  dunst -verbosity info
```

Compositor Hikari:
```
~ $ wayland-info                                                                 
interface: 'wl_shm',                                     version:  1, name:  1
interface: 'wl_drm',                                     version:  2, name:  2
interface: 'zwp_linux_dmabuf_v1',                        version:  3, name:  3
interface: 'wl_compositor',                              version:  4, name:  4
interface: 'wl_subcompositor',                           version:  1, name:  5
interface: 'wl_data_device_manager',                     version:  3, name:  6
interface: 'zxdg_output_manager_v1',                     version:  3, name:  7
interface: 'zwlr_gamma_control_manager_v1',              version:  1, name:  8
interface: 'zwlr_screencopy_manager_v1',                 version:  3, name:  9
interface: 'org_kde_kwin_server_decoration_manager',     version:  1, name: 10
interface: 'zxdg_decoration_manager_v1',                 version:  1, name: 11
interface: 'zwlr_data_control_manager_v1',               version:  2, name: 12
interface: 'gtk_primary_selection_device_manager',       version:  1, name: 13
interface: 'zwp_primary_selection_device_manager_v1',    version:  1, name: 14
interface: 'wl_seat',                                    version:  7, name: 15
interface: 'xdg_wm_base',                                version:  2, name: 16
interface: 'zwlr_layer_shell_v1',                        version:  2, name: 17
interface: 'wl_output',                                  version:  3, name: 18
```

**Comment by fwSmit** [comment] 2020-11-28 22:39
I didn't know that weston-info was deprecated, I never read the first few lines of output. Arch doesn't even have it in the main repos yet.

>Running the dunst command at least offered the information what output is used. Looking good so far. The following line not so much. Dunno what is at fault.

Good to see that wayland is detected correctly at least. Does dunst also crash when not using `-verbosity info`?

The idle protocol is called 'org_kde_kwin_idle', so hikari doesn't support it yet. This should be handled gracefully, though.

**Comment by Narrat** [comment] 2020-11-28 23:12
Propably only a matter of time. I pushed at least the respective PKGBUILDs for wayland-utils to the aurweb.

>Does dunst also crash when not using -verbosity info?

Yes, dunst also crashes in this case. So propably unrelated?

>The idle protocol is called 'org_kde_kwin_idle', so hikari doesn't support it yet. This should be handled gracefully, however.

Time will tell if it is handled gracefully ;) But so far so good (Casually "using" dunst like before)

**Comment by fwSmit** [comment] 2020-11-29 12:50
If it crashes, how are you using it then?

**Comment by Narrat** [comment] 2020-11-29 18:20
I would guess D-Bus interface(?) is working correctly? Creating notifications via `notify-send` works fine.
But it should be something I could bisect. I tried regular `dunst 1.5.0` and invoking `dunst` works fine. Installing the `wayland-2` based git build and the `dunst` command segfaults as before.

**Comment by Narrat** [comment] 2020-11-29 18:54
Hrm.. Dunno what went wrong. My assumption is, that it is somehow related to the dunst-git PKGBUILD or magic. First build breaks reliable, but a newly created package (with modified PKGBUILD) and local builds work fine. So the segfault can be disregarded. Something on my end that went wrong.

**Comment by fwSmit** [comment] 2020-11-29 22:02
That's weird. Did you change the PKGBUILD to point it to the right branch as well? The master branch is the same as the dunst master. 
Could you run `pacman -Qi dunst-git` to check if you are using right version? I've recently added some more things, so could you update to the latest version? And to be sure you are not running an older version of dunst accidentally, I would recommend to remove dunst 1.5.0. It can indeed be started automatically via D-Bus.

All features should be present in the latest commit, so it's a matter of improving the stability now. If you run into any issues, please let me know and send output of `dunst -verbosity debug`. Thanks for helping.

**Comment by Narrat** [comment] 2020-12-02 20:46
> That's weird. Did you change the PKGBUILD to point it to the right branch as well? The master branch is the same as the dunst master.

Of course. Else it wouldn't have been possible to get the output regarding the actively used wayland output. I additionally synchronized for the next build (which was then working) the PKGBUILD with the one from community. The -git is in this regard a little bit out of date (but not outrightly broken).

> Could you run `pacman -Qi dunst-git` to check if you are using right version? I've recently added some more things, so could you update to the latest version? And to be sure you are not running an older version of dunst accidentally, I would recommend to remove dunst 1.5.0. It can indeed be started automatically via D-Bus.

Did make sure that there weren't conflicting dunst versions running. But who knows, maybe I forgot it once. At least stable vs dev build isn't a problem, as the -git package rightly conflicts the repo package. So all the time only one dunst binary available (systemwide).
Currently running a build based on commit 639447e (`dunst-git 1.5.0.r46.g639447e-1`). Next time it will updated to a build based on 8299f86

> All features should be present in the latest commit, so it's a matter of improving the stability now. If you run into any issues, please let me know and send output of `dunst -verbosity debug`. Thanks for helping.

Will do :) And thanks for your work in adding this feature :)

**Comment by tsipinakis** [comment] 2020-12-05 20:42
#781 is now marked for review (which I'll do shortly). Since I'm not a wayland user myself I'd appreciate it if anyone that's interested in this switches to using that branch locally to test and point out any existing issues.

**Comment by Narrat** [comment] 2020-12-16 18:37
And another curious case :D
With a build based on 7c2f56f dismissing a notification window via mouseclick just causes said window to flicker.
Starting dunst with `-verbosity debug` and dismissing works fine.

**Comment by fwSmit** [comment] 2020-12-16 19:02
Thanks for reporting. There is a known bug in the current wayland build that looks as you describe (it's also on the current master btw). That is only when using X11 output, however (at least on xwayland it's broken, I'm not sure about X11). Tsipankis has already made a fix for it, but he didn't yet push it to master.
Are you using the X11, xwayland or wayland output?
Also, the verbosity should have no effect on the drawing, so that's weird.

**Comment by Narrat** [comment] 2020-12-16 19:15
If autodetect is working for the dbus interface it should be the wayland output. In the worst case xwayland.

Verbose output when manually started. I'm wondering about those `output is null` entries?
```
$ dunst -verbosity debug                                                       
INFO: Using Wayland output
INFO: New output 18 - id 0
INFO: compositor doesn't support org_kde_kwin_idle_interface
INFO: Adding pointer
DEBUG: RUN
INFO: Idle status queried: 0
INFO: Calling win_hide
INFO: Wayland: Hiding window
DEBUG: Waking up
DEBUG: RUN
INFO: Idle status queried: 0
DEBUG: Screen size: 1920x1080
DEBUG: Return value: 1590x20
INFO: output is null
DEBUG: Wl: Window dimensions 300x38
DEBUG: Wl: Window position 1590x20
DEBUG: Surface handle configure 300x38
DEBUG: Sleeping for 9988 ms
DEBUG: RUN
INFO: Idle status queried: 0
DEBUG: Queues: Closing notification for reason: time
INFO: Calling win_hide
INFO: Wayland: Hiding window
DEBUG: Waking up
DEBUG: RUN
INFO: Idle status queried: 0
DEBUG: Screen size: 1920x1080
DEBUG: Return value: 1590x20
INFO: output is null
DEBUG: Wl: Window dimensions 300x38
DEBUG: Wl: Window position 1590x20
DEBUG: Surface handle configure 300x38
DEBUG: Sleeping for 9999 ms
DEBUG: RUN
INFO: Idle status queried: 0
DEBUG: Queues: Closing notification for reason: time
INFO: Calling win_hide
INFO: Wayland: Hiding window
```

**Comment by fwSmit** [comment] 2020-12-16 19:35
The flickering shouldn't happen when using X11 output as far as I know. If you're using a wayland compositor, this can only be when you use the current master branch of dunst or you force xwayland with `dunst -force_xwayland`.

You probably still have another version of dunst installed on your system? If dunst is started with dbus, the system wide installation installation is started. To check, you can run `dunstify -s`. This will give you the version of the current running dunst.

Don't worry about the output being null. That's just saying that dunst will redraw. I will remove most debug prints before releasing to prevent confusion.

**Comment by Narrat** [comment] 2020-12-16 19:49
And what about the different behaviour? In one case there is a timeout of the notification (manually started) and in the non-working this isn't happening.

And `dunstify` reports for both cases (working and non-working):
```
$  dunstify -s                                                                 
name:dunst
vendor:knopwob
version:v1.5.0-56-g7c2f56f
spec_version:1.2
```
And this is the only installed dunst. I don't install software manually. Don't like it if stuff isn't covered by the package-manager.

>Don't worry about the output being null. That's just saying that dunst will redraw. 

Good to know.

**Comment by fwSmit** [comment] 2020-12-16 21:46
> And `dunstify` reports for both cases (working and non-working):
> 
> ```
> $  dunstify -s                                                                 
> name:dunst
> vendor:knopwob
> version:v1.5.0-56-g7c2f56f
> spec_version:1.2
> ```

That's the right version.

> And what about the different behaviour? In one case there is a timeout of the notification (manually started) and in the non-working this isn't happening.

I wasn't able to reproduce this. I'm on arch, and I even installed hikari. Could you try to bisect it and to see if the bug is always present?

**Comment by Narrat** [comment] 2020-12-17 17:45
Always present, but today without the flickering window (yeah, I dunno). What remains: I cannot close the notification window without killing dunst if started via dbus.
And this happens with all builds based after https://github.com/fwSmit/dunst/commit/ed1e3a815a9f80bdd1591faaa8eaa25a70d6b9d4

**Comment by tsipinakis** [comment] 2020-12-17 17:52
This seems to be related to a faulty bugfix. I pushed to master a correction now, the wayland branch just needs to be rebased.

**Comment by fwSmit** [comment] 2020-12-17 21:38
> Always present, but today without the flickering window (yeah, I dunno). What remains: I cannot close the notification window without killing dunst if (auto-)started via dbus.
> And this happens with all builds based on and after [fwSmit@ed1e3a8](https://github.com/fwSmit/dunst/commit/ed1e3a815a9f80bdd1591faaa8eaa25a70d6b9d4)

The wayland branch is now rebased. Could you try if this fixes it?

**Comment by Narrat** [comment] 2020-12-17 22:14
The fixes from master do the trick. New build and I can dismiss notifications again :)

**Comment by flipflop133** [comment] 2020-12-26 08:07
I'm running an issue with sway on Fedora 33:
notifications stay forever if I don't set idle_threshold = 0
If I run dunst -verbosity info, I get the following output:
Xlib:  extension "MIT-SCREEN-SAVER" missing on display ":0".

**Comment by tsipinakis** [comment] 2020-12-26 11:01
It looks like it's using XWayland which doesn't support idle. Do you have `force_xwayland` enabled? With `-verbosity debug` what output does it say it uses? (It should say in the first few lines on startup).

**Comment by flipflop133** [comment] 2020-12-26 13:34
`
➜  ~ sway -verbosity debug
sway version v1.5
➜  ~ sway
2020-12-26 14:32:42 - [main.c:299] Found config * for output WL-1 ((null))
glamor: No eglstream capable devices found
[2020-12-26 14:32:42.609] [info] Resources files: /home/francois/.config/waybar/config, /home/francois/.config/waybar/style.css
[2020-12-26 14:32:42.615] [warning] module battery#bat2: Disabling module "battery#bat2", No battery named BAT2
[2020-12-26 14:32:42.616] [warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Internal error:   Could not resolve keysym XF86FullScreen
Errors from xkbcomp are not fatal to the X server
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
> Internal error:   Could not resolve keysym XF86FullScreen
Errors from xkbcomp are not fatal to the X server
Xlib:  extension "MIT-SCREEN-SAVER" missing on display ":1".
[2020-12-26 14:32:42.711] [info] Bar configured (width: 909, height: 35) for output: WL-1
`
I tried all xwayland values it doesn't change anything (I just reloaded config, so I don't know if it was enough).

**Comment by tsipinakis** [comment] 2020-12-26 14:26
Idle doesn't work with Xwayland, it's not supported.

What's the output of `dunst -version`? Are you running the experimental wayland branch or the official release?

**Comment by flipflop133** [comment] 2020-12-26 14:29
Oh ok I wasn't aware that it wasn't supported, is there any alternative?
dunst version is 1.4.1
I'm using the official wayland branch

**Comment by fwSmit** [comment] 2020-12-26 15:05
> Oh ok I wasn't aware that it wasn't supported, is there any alternative?
> dunst version is 1.4.1
> I'm using the official wayland branch

There are two wayland branches. It looks like you're using the wayland branch in this repo. It's is old and should not be used. Use the `wayland-2` branch from #781 instead.
If you still have problems with notifications not disappearing, please report back :)

**Comment by flipflop133** [comment] 2020-12-26 18:19
Damn! Good job, everything works perfectly, hope it'll be merged in master.
I just had to modify the makefile to be able to build because there was an issue on line 36.

**Comment by fwSmit** [comment] 2020-12-26 20:03
> Damn! Good job, everything works perfectly, hope it'll be merged in master.

Thank you! It's finished now, so it will get merged as soon as @tsipinakis gets to it.

> I just had to modify the makefile to be able to build because there was an issue on line 36.

This is worth getting fixed before merging into master. What was the issue and how did you fix it?

**Comment by flipflop133** [comment] 2020-12-26 20:16
Nice!
Yeah it is worth fixing before merging I think because without editing the makefile it wasn't building, sorry it's on line 39, it is bad indentation issue. But I removed the line because the condition got entered after fixing so I wasn't able to build without removing this error message.

**Comment by flipflop133** [comment] 2020-12-26 21:29
I noticed another issue that is related to wayland I think is that notifications doesn't show up when applications are in fullscreen mode.
Tested on https://github.com/fwSmit/dunst/tree/wayland-2

**Comment by fwSmit** [comment] 2020-12-26 22:11
> Nice!
> Yeah it is worth fixing before merging I think because without editing the makefile it wasn't building, sorry it's on line 39, it is bad indentation issue. But I removed the line because the condition got entered after fixing so I wasn't able to build without removing this error message.
> EDIT: link: https://github.com/fwSmit/dunst/blob/wayland-2/Makefile#L39

Oh yeah that's because you don't have wayland-protocols installed. It's currently not neccesary for building dunst, but it may be in the future. I'll make it optional for now. 



> I noticed another issue that is related to wayland I think is that notifications doesn't show up when applications are in fullscreen mode.
> Tested on https://github.com/fwSmit/dunst/tree/wayland-2

That shouldn't happen. Could you try again with `dunst -layer overlay`? This should be the default, but maybe it doens't get set correctly.

**Comment by flipflop133** [comment] 2020-12-27 08:30
Yeah indeed it's working perfectly with `dunst -layer overlay`, thanks again for your help and work!

**Comment by fwSmit** [comment] 2020-12-27 16:10
> Yeah indeed it's working perfectly with `dunst -layer overlay`, thanks again for your help and work!

Great. This should be the default, however. So either you are using an older version, or something goes wrong. Are you using https://github.com/fwSmit/dunst/commit/4a3618bb3a53a5fadaf81629dabb0749929b7ff0 or and older version?

**Comment by fwSmit** [comment] 2020-12-28 15:47
> Nice!
> Yeah it is worth fixing before merging I think because without editing the makefile it wasn't building, sorry it's on line 39, it is bad indentation issue. But I removed the line because the condition got entered after fixing so I wasn't able to build without removing this error message.
> EDIT: link: https://github.com/fwSmit/dunst/blob/wayland-2/Makefile#L39

This is fixed now. You should be able to build it without wayland-protocols installed. You can also build dunst without wayland support with `make WAYLAND=0`.

**Comment by fwSmit** [comment] 2021-01-19 10:14
The wayland PR is now merged in master.

**Comment by tsipinakis** [comment] 2021-01-19 11:52
Implemented via #781 .

**Closed** 2021-01-19 11:52 UTC
Labels: Feature, graphics, help wanted

**Comment by christiansacks** [comment] 2023-11-13 09:18
Late to the party but I am having the same issue as OP, I just recently switched to Wayland/Sway from X11/i3 and dunst is "working" in that notifications show as intended, but closing using the mouse is hit or miss, sometimes it will work ok, and other times left/right clicking on the notification will just pass that left/right click through to the window beneath the notification.

I have set up a keybinding in sway's config that just runs `dunstctl close-all` which helps, but would be nice to be able to click the notifications to clear them too.

I noticed that they don't automatically disappear like they did with X11/i3 after a certain amount of time.

**Comment by Narrat** [comment] 2024-01-27 19:35
@christiansacks maybe your issue, if it is still of relevance, is also solved by the on-going work in https://github.com/dunst-project/dunst/pull/1250

**Comment by christiansacks** [comment] 2024-01-27 19:37
> @christiansacks maybe your issue, if it is still of relevance, is also solved by the on-going work in https://github.com/dunst-project/dunst/pull/1250

Yes could be, I've sinced been using swaync and actually finding it really useful.
