### ISSUE TITLE
dunst does not exit after exiting sway

### ISSUE THREAD

**Issue by jmcantrell** [dunst-project/dunst#901] opened 2021-09-09 16:04 UTC
I have sway set to start dunst with `exec dunst`. The first time a sway session is started, everything works fine. After exiting with `swaymsg exit`, I noticed that dunst is still running.

When starting another sway session (without rebooting), presumably sway tries to start dunst again and gets a message similar to `CRITICAL: Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'dunst' with PID '154126'.`

I can work around this by adding a `killall dunst` to the exec command in the sway config, but this seems hacky. Using i3 and startx, dunst is not left running after exiting.

Admittedly, I'm new to sway and wayland, so if there's something I'm missing, I'd be grateful to be pointed in the right direction, as I was not able to find anything similar.

### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon 1.6.1 (2021-02-21)
`
- Install type: `package`
- Distro and version: `arch`

**Comment by fwSmit** [comment] 2021-09-10 13:36
Duplicate of #851. Sway itself doesn't do process management. It's not considered a bug on their side. There is a temporary solution mentioned in the linked issue, but I heard it's also possible for wayland apps to detect that the compositor has exited. I just haven't figured out how exactly.

**Closed by fwSmit** 2021-09-10 13:36 UTC
