### ISSUE TITLE
right-to-left text alignment issue

### ISSUE THREAD

**Issue by Nervengift** [dunst-project/dunst#261] opened 2016-05-05 19:44 UTC
![20160505210006](https://cloud.githubusercontent.com/assets/2066508/15053920/3ee32644-1305-11e6-8966-825687538bba.png)

The title here should be aligned to the left as defined in the config, even if I'm not sure what the best behavior for right-to-left only text would be...

Also it should read "קנאָבל אָפּצאָל liked"

Script for testing behavior (best viewed in gedit or something the like, .txt because Github) [dunst-rtl.sh](https://github.com/knopwob/dunst/files/251070/dunst-rtl.txt)

**Comment by fwsmit** [comment] 2022-01-16 17:22
This still exists and I'm not sure if this is the right behaviour. It's most likely caused by pango ( the text rendering library). If you still think it's a bug, I would suggest sending a bug report to pango. Either way, I'll close this, as we cannot do much about it.

**Closed by fwsmit** 2022-01-16 17:22 UTC
Labels: Bug
