### ISSUE TITLE
[Request] Override support more settings

### ISSUE THREAD

**Issue by Link-Satonaka** [dunst-project/dunst#255] opened 2016-02-08 06:25 UTC
I'd like to be able to override geometry for individual sections. If this is being implemented, might as well include override support for the other visual settings too.

Thanks!

**Comment by tsipinakis** [comment] 2017-01-14 21:09
Duplicate of #265 
Even though this issue is older I am closing it in favour of #265 since there have been more replies there.

**Closed by tsipinakis** 2017-01-14 21:09 UTC
