### ISSUE TITLE
Notifications not timing out/closing by themselves

### ISSUE THREAD

**Issue by xwhatsit** [dunst-project/dunst#132] opened 2013-11-21 03:28 UTC
I'm running dwm with two monitors. Despite using the following config options (I think these are the only relevant ones):

```
idle_threshold = 0 
sticky_history = no

[urgency_low]
    timeout = 2

[urgency_normal]
    timeout = 2

[urgency_critical]
    timeout = 2
```

...I still have notifications linger for much longer than the 2 seconds specified, if X isn't interacted with. If I do one of the following:
- Change window focus between monitors (using mouse or keyboard)
- Change current dwm tag
- Raise/lower volume using keypresses (which seems to cause the current window to briefly lose focus, perhaps an artifact how xbindkeys works)
- Set the rootname (changing the dwm status bar)—this happens every 60 seconds to update a clock display
- Click the notification itself with the mouse

...then the lingering notification will disappear.

I'm using dunst 1.0.0. Let me know if there's any more information I can provide.

**Comment by amerlyq** [comment] 2016-03-13 20:36
Moreover, in #109 was changed timer resolution from milliseconds to seconds.
It has sense for long timeout > 5 seconds, but is fatal for short ones ~ 1-2 seconds.
I'm truly liked to use dunst for short notify around 1.2s.
But, of course, --expire-time=1200 don't work and instead shows message for at least ~3s.
So, why there is that low border? I even can't specify 1s timeout despite all of that!

**Comment by tsipinakis** [comment] 2017-01-17 11:41
Since this is quite old and I can't reproduce in HEAD I am closing this. Feel free to reopen(or create a new one) if it's still an issue.

**Comment by allannk** [comment] 2017-11-07 10:51
This issue still seems to be present. 
I'm running i3 window manager, with timeouts of 3, 20, infinity (low, normal, critical respectively). 
With multiple windows open, messages are removed only when I change window focus (hovering messages is not enough).
Let me know what kind of debug information I could provide

**Comment by bebehei** [comment] 2017-11-07 11:06
@allannk I've got the same problem. At some point notifications aren't removed from display. But sadly, I can't reproduce it. Do you have any (at least on your system) reproducible test?

**Comment by allannk** [comment] 2017-11-07 13:13
I can't say this is very scientific, though, but I'm creating a notification in python from a terminal. 
It seems, that if I trigger a notification and *keep* the mouse (and thus focus) on this terminal, the notifications seem to hang around indefinitely or until I move the mouse (and focus) away from the terminal. If I trigger the notification, and focus another window *before* the timeout, notifications are cleared as they should once they reach timeout.

**Comment by bebehei** [comment] 2017-11-07 14:21
@allannk I've found a testcase for this. Sending a notification with 10s and 1s timeout will invoke the notification close on right time, but won't undisplay the nofitication with 1s and removes all notifications from the display when the 10s notification times out.

```
notify-send -t 1000 asdf asdf1
notify-send -t 10000 asdf asdf10
```

Can you reproduce this?

---

Just to not step into any tarpits: What version do you use?

**Comment by allannk** [comment] 2017-11-07 14:46
Using dunst 1.2.0 (Arch Linux community repo)
Actually, I cannot seem to reproduce with the behavior with the notify-send command, with or without the `-t` option. I'll have to test this a bit more

**Comment by bebehei** [comment] 2017-11-07 15:26
My problem does not come from the same source. I've split my issue into a separate one. Please gather some data to reproduce the problem.

**Closed** 2017-12-02 06:56 UTC
Labels: Bug, waiting-for-info
