### ISSUE TITLE
Getting context hangs dunst

### ISSUE THREAD

**Issue by wpovell** [dunst-project/dunst#456] opened 2017-12-13 06:01 UTC
notify-send www.example.com
(Notif appears, ctrl-shift-period to get context, nothing happens)
notify-send test
(Now no notifications work at all)

Tried with browser set to both google chrome stable and firefox nightly.

### Installation info

dunst-git from AUR
OS: Linux arch 4.14.4
notify-send 0.7.7

**Comment by bebehei** [comment] 2017-12-13 07:19
Could you please run `killall dunst; dunst -print` on the command line, reproduce the stuff and paste the output of dunst?

Dunst should spit out some warnings here.

Also, what's your `dmenu_path` setting (and where does it point to)?

**Comment by bebehei** [comment] 2017-12-30 02:17
@wpovell Any news on this?

**Comment by wpovell** [comment] 2017-12-30 15:55
@bebehei Sorry for not getting back to you! My old laptop died so can't check the setup, but if I remember correctly the dmenu_path was `/usr/bin/rofi` and even when running with `-print` no errors were shown before hanging, just the standard message when a browser notification got sent (sorry I don't have it to share, can update again when I get a new laptop on the 3rd).

**Comment by bebehei** [comment] 2018-01-11 01:57
Ok, I can reproduce the problem. Much easier: `dunst -dmenu "sleep 20"`. This will simply make dunst halt for 20s. After 20s dunst then goes on and processes all incoming messages then responds again.

I guess we have to fork before dmenu and just to open the browser.

**Comment by tsipinakis** [comment] 2018-01-11 05:18
> I guess we have to fork before dmenu and just to open the browser.

We are forking for both dmenu and the browser but we wait for dmenus result (to issue the proper command) and to collect the exit status to avoid leaving zombie processes around.

To fix this we'd have to move all this logic into the main loop like `check_timeouts` etc.

**Comment by bebehei** [comment] 2018-01-11 14:11
Well, yeah. Probably we have to do this. As long as dmenu is opened, dunst can't do anything. Because most of the programs on the desktop rely on the notification daemon to be responsive, all other programs hang. Of course, when interactively using dmenu, the user doesn't see this and it's not a tragedy, if the user handles dmenu quickly. But if things go south, the user doesn't know what's going on and also does not see any error message.

I just want to remind you of your IRC client, when you tested something with dunst and your IRC connection timed out, because your client couldn't send notifications.

**Comment by tsipinakis** [comment] 2018-01-12 20:09
> My old laptop died so can't check the setup, but if I remember correctly the dmenu_path was /usr/bin/rofi

You did use the `-dmenu` parameter with rofi right? Dunst only supports dmenu or drop-in replacements with the context menu and using anything else simply won't work.

**Comment by bebehei** [comment] 2018-01-12 21:10
> You did use the -dmenu parameter with rofi right? Dunst only supports dmenu or drop-in replacements with the context menu and using anything else simply won't work.

Rofi is a [proper dmenu replacement](https://github.com/DaveDavenport/rofi#dmenu). And it works, but do not forget the `-dmenu` argument. (@wpovell have you done this?)

I've tested it now, it works. (It works so good, that I won't use dmenu anymore).

**Comment by wpovell** [comment] 2018-01-12 23:01
Yup adding -dmenu fixes it, thanks.

**Comment by bebehei** [comment] 2018-01-23 16:50
The solution for this has to be thread and memory safe. (The notification could have timed out in meantime and already freed if there is no history active). Also a plain copy of the notification should not be done, as the `NotificationClosed` signal could have been sent in meantime.

I guess, I've got a solution for this:

Implement `GObject` functionality in the notification type.

In the `context_menu`, split out the blocking part into a separate `GThread` and hold inside this thread a weak reference to the notification.

When the notification is timed out/forcefully closed in the meantime, the weak reference is `NULL` and therefore we know, the notification/action is invalid.

Cases left to handle:

- The notification is in history (weak ref != `NULL`, but `NotificationClosed` signal already sent).
    - Add a `closed` field in the notification type and set this to `true` on the first `notification_closed` call.
- The notification times out automatically, while the user hasn't chosen the dmenu entry yet.
    - Not sure about this yet. Maybe do not timeout the notifications temporarily until `dmenu` returns. But accept forceful closes (click on the notification).

**Comment by bebehei** [comment] 2018-07-07 09:31
I've fixed this thing.

I did **not** use `GObject`. I used manual refcounts with GLib's [atomic integers](https://developer.gnome.org/glib/stable/glib-Atomic-Operations.html).

It works :tm: currently on my machine. Now, it needs some testing and commit polishing before I fire it as a PR.

The branch: https://github.com/dunst-project/dunst/compare/master...bebehei:threaded-dmenu

**Closed** 2018-10-10 14:49 UTC
Labels: Bug
