### ISSUE TITLE
Markdown is broken

### ISSUE THREAD

**Issue by Squidamatron** [dunst-project/dunst#618] opened 2019-04-03 03:59 UTC
Markdown fails to parse properly in the most recent release. Instead of showing bold text in the output, it will instead literally show `<b>text</b>` in the notification.

`dunst -print` differences between versions:
#### 1.3.2-2
```
{
	appname: 'notify-send'
	summary: 'hello <b>bold hello</b>'
	body: ''
	icon: 'dialog-information'
	raw_icon set: false
	category: 
	timeout: 3000
	urgency: NORMAL
	transient: 0
	formatted: 'hello <b>bold hello</b>'
	fg: #C5C8C6
	bg: #282A2E
	frame: #C5C8C6
	id: 2
	script: (null)
}

```
#### 1.4.0
```
{
	appname: 'notify-send'
	summary: 'hello <b>bold hello</b>'
	body: ''
	icon: 'dialog-information'
	raw_icon set: false
	icon_id: '(null)'
	desktop_entry: ''
	category: 
	timeout: 3000
	urgency: NORMAL
	transient: 0
	formatted: 'hello &lt;b&gt;bold hello&lt;/b&gt;'
	fg: #C5C8C6
	bg: #282A2E
	frame: #C5C8C6
	fullscreen: show
	progress: -1
	stack_tag: 
	id: 2
	actions: {}
	script: (null)
}
```

### Installation info

- Version: `1.4.0 (2019-03-30)`
- Install type: `package`
- Distro and version: `Arch`

**Comment by tsipinakis** [comment] 2019-04-03 08:24
Duplicate of #616.

Markup was disabled in the summary because it went against the notification spec and caused problems with some clients.

```
notify-send 'hello' 'hello <b>bold hello</b>'
```
stills works.

**Closed by tsipinakis** 2019-04-03 08:24 UTC
