### ISSUE TITLE
Notification doesn't disappear despite timeout set

### ISSUE THREAD

**Issue by plomari** [dunst-project/dunst#1032] opened 2022-02-16 10:11 UTC
### Issue description

This is my config file, and from the font I can see that it's actually used:
```
[global]
width = 500
height = 200
scale = 2
font = "Verdana 30"
history_length = 5
timeout = 1
```

But the notification which some other program just sent didn't disappear after about 30 seconds. Notifications sent with `notify-send` disappear after 1 second.

What gives?

Maybe the dunstrc isn't "what I wanted", but it was hard enough to figure out that much.

### Installation info

- Version: Dunst - A customizable and lightweight notification-daemon v1.7.3-47-gb56e7da
- Install type: manually

**Comment by fwsmit** [comment] 2022-02-16 10:53
What's the output of `dunst -print`. I think the program in question sets the timeout via dbus, which overrides the timeout of the config.

**Comment by fwsmit** [comment] 2022-02-16 10:54
Might be related to #1020

**Comment by plomari** [comment] 2022-02-16 11:02
> What's the output of dunst -print. I think the program in question sets the timeout via dbus, which overrides the timeout of the config.

I won't know until it produces such a notification again. Normally, the notifications from the same program disappear correctly, and this was apparently a special case.

**Comment by plomari** [comment] 2022-03-20 11:35
I have now determined that it happens sporadically with "notify-send text" (no further arguments). So far it happens twice within a month.

**Comment by fwsmit** [comment] 2022-03-23 11:00
Yeah I noticed that issue as well. It's hard to track down, though, since it doesn't happen very often. When it happens, could you run `dunstctl count displayed` to see if dunst still thinks the notifications are displayed.

I also noticed that when a new notification appears, the stuck notification does disappear.

**Comment by plomari** [comment] 2022-03-23 11:04
I can add that when it happened, I used `dunstctl close`, which removed the message.

**Comment by fwsmit** [comment] 2022-03-23 11:08
Yep, that's also a thing that worked for me. I suspect dunst is somehow sleeping before it's time to close the notification and doesn't wake up anymore.

**Comment by plomari** [comment] 2022-03-26 18:17
Happened again with notify-send.

> dunstctl count displayed

Prints `1`, and the message remains displayed on screen.

**Comment by fwsmit** [comment] 2022-03-29 05:07
Thanks for reproducing. So I conclude from that info that the error isn't on the display side, but it occurs before closing the notification. Or there is some kind of error in the queues.

It's a tough issue to solve, so more information is better. Could you maybe collect debug information from the issue happening? You can run dunst with `dunst -verbosity debug 2>&1 > /tmp/dunst.log` and when the issue happens, copy the debug log and send it here.

@tsipinakis @bebehei do you have any insight in this issue? I think it has existed for a while and you might have debugged it before.

**Comment by bebehei** [comment] 2022-03-29 05:58
No clue from my side.

**Comment by peterfab9845** [comment] 2022-04-02 02:10
I've been experiencing the same issue from time to time, and I set up the logging as mentioned.

The log file is attached - it's pretty big, as dunst was running for a while before it happened; the key point seems to be around line 36190, where it says "Sleeping for 0 ms" and then doesn't close anything until a little over a minute later. (I believe this minute is the time until I made another notification by pausing my media).
There are some other places where "Sleeping for 0 ms" appears, but the notification usually gets closed immediately after.

[dunst.log](https://github.com/dunst-project/dunst/files/8401595/dunst.log)

**Comment by peterfab9845** [comment] 2022-04-04 19:23
Just got another one, seeing the same behavior in the log: "Sleeping for 0 ms" at line 2618, and then dunst doesn't wake back up until I get another notification 3 minutes later (line 2977). At that point the old notification is immediately closed.
While the notification was stuck, `dunstctl count` gave the following output:
```
$ dunstctl count
              Waiting: 0
  Currently displayed: 1
              History: 6
```
[dunst2.log](https://github.com/dunst-project/dunst/files/8412577/dunst2.log)

**Comment by fwsmit** [comment] 2022-05-06 12:38
@plomari @peterfab9845 are you using wayland. If so, your issue may be the same as #1066. Going off of the bug reports, it seems to be solved in master now.

**Comment by fwsmit** [comment] 2022-05-09 10:44
Thanks for confirming. I think I figured out this issue. It has to do with the timeouts being shorter than expected. This can be simulated with:

```patch
diff --git a/src/dunst.c b/src/dunst.c
index cb58dc5..deff427 100644
--- a/src/dunst.c
+++ b/src/dunst.c
@@ -99,7 +99,7 @@ static gboolean run(void *data)
 
                 if (sleep >= 0) {
                         if (next_timeout < now || timeout_at < next_timeout) {
-                                g_timeout_add(sleep/1000, run, NULL);
+                                g_timeout_add(sleep/1100, run, NULL);
                                 next_timeout = timeout_at;
                         }
                 }
```

Since there are no guarantees given on the accuracy of the timeouts, this is well possible. A simple patch that will make sure all notifications time out eventually is:

```patch
diff --git a/src/dunst.c b/src/dunst.c
index cb58dc5..f96ae0f 100644
--- a/src/dunst.c
+++ b/src/dunst.c
@@ -101,6 +101,8 @@ static gboolean run(void *data)
                         if (next_timeout < now || timeout_at < next_timeout) {
                                 g_timeout_add(sleep/1000, run, NULL);
                                 next_timeout = timeout_at;
+                        } else {
+                                return G_SOURCE_CONTINUE;
                         }
                 }
         }
```

A downside is that this causes too many wake ups in multi-notification scenarios. Another downside is that in the cases where this bug happens, the notification will timeout in about twice the time, not the normal duration.

I'm looking at figuring out a better way of fixing this issue, but know that a fix is on it's way.

**Comment by fwsmit** [comment] 2022-05-09 13:16
@plomari @peterfab9845 I made a PR with a fix for this issue. Could you test it out and report if this fixes it and no new issues were added?

**Comment by fwsmit** [comment] 2022-05-13 14:29
I'm merging it now. Let me know if you see this issue again or any other issues appear

**Closed by fwsmit** 2022-05-13 14:29 UTC
Labels: Bug

**Comment by peterfab9845** [comment] 2022-06-01 07:15
Just a status update, I have been running the version from this PR since the 9th and haven't seen the issue at all. It seems the fix is working well. Thank you!

**Comment by fwsmit** [comment] 2022-06-01 07:25
Great to hear and thank you for the update. I did notice a slight issue with Dunst not sleeping correctly, but that doesn't cause any issues like this one.
