### ISSUE TITLE
Multiple fonts not working together

### ISSUE THREAD

**Issue by astridbunny** [dunst-project/dunst#1211] opened 2023-10-17 01:16 UTC
### Issue description
I want to use a symbol font together with a text font for notifications.
If I put the fonts in the order: 
`font = "mononoki 8, Material Icons 8"`
Text does not show up at all, only the icons.
However, the order:
`font = "Material Icons 8, mononoki 8"`
Has the opposite problem: icons will not show up at all. I'm unsure what could be causing this.

### Installation info

- Version: `<!-- output of dunst -v -->`
Dunst - A customizable and lightweight notification-daemon 1.9.2 (2023-04-20)
- Install type: `<!-- [package|manually|...] -->`
Package manager
- Window manager / Desktop environment: `<!--  -->`
i3-gaps
- Distro: `<!--  -->`
Void Linux

**Comment by astridbunny** [comment] 2023-10-17 21:43
"Fixed" the issue by merging the fonts in FontForge, but still unsure why this is happening.

**Comment by bynect** [comment] 2023-10-25 12:36
I have the same problem with fontawesome. I think that it's related to the way pango loads fonts. Needs further investigation

**Comment by bynect** [comment] 2023-10-28 12:38
Pango cairo seems to support loading only one font at a time. I made a pr for font fallback that should mitigate this (given that fontconfig is correctly configured). Alternatively specifying which font to use with pango markup should also work

**Comment by fwsmit** [comment] 2024-02-16 11:58
This should be mostly fixed with #1222. Are there any issues remaining?

**Comment by bynect** [comment] 2024-03-01 22:43
I have looked more into it, and this seems by design. Pango is made so that if you want to use multiple fonts you have to specify the fallbacks with fontconfig and they will be used as necessary, so that the font is not chosen at the application level but globally.

I will close this as we can't really do anything else without abandoning pango

**Closed by bynect** 2024-03-01 22:43 UTC
