### ISSUE TITLE
Adding actions via rules

### ISSUE THREAD

**Issue by ohle** [dunst-project/dunst#784] opened 2020-11-27 07:53 UTC
This is a feature suggestion:

Would it be possible to add a way to add actions (rather than immediate scripts) via a rule? This is apparently what #394 was about, but that ticket quickly shifted to bugs around standard actions.

The idea is to retrofit actions onto notifications sent by applications that don't supply them themselves and are hard to change. Or even supply custom actions (perhaps based on content keywords) that go beyond what an application could supply.

**Comment by tsipinakis** [comment] 2020-11-27 09:51
Duplicate of #669, see also #753 for a different take.

I'm open to adding this but currently don't have time to develop new features. I'd accept a PR if anyone wants to work on it.

**Closed by tsipinakis** 2020-11-27 09:51 UTC
