### ISSUE TITLE
RGBA Support

### ISSUE THREAD

**Issue by jonathashenriques** [dunst-project/dunst#429] opened 2017-11-04 02:34 UTC
Is there a way to use RGBA colors in `Dunst` ?

**Comment by tsipinakis** [comment] 2017-11-04 04:43
Duplicate of #289. Relevant discussions in #344 and #180 

The quick answer: No, it turned out to be much more complicated than it looked to convert #RGB to #RGBA

**Closed by tsipinakis** 2017-11-04 04:43 UTC
