### ISSUE TITLE
Is it possible to run a script when clicking on a notification ? How?

### ISSUE THREAD

**Issue by rainer2208** [dunst-project/dunst#1149] opened 2023-03-06 14:42 UTC
Hi all, I am on Arch Linux. 

For some time I am reading all I can find about configuring dunst to run a script when clicking on a notification, but all my efforts have been, so far, unfruitful. 

From my readings, is seems that running scripts from clicking on notifications should definitely be working in dunst. 

Consulting the [Arch Wiki site](https://wiki.archlinux.org/title/Dunst#Actions) , one can configure the mouse click to do some sort of close action. 

There is also a possibility do define a `mouse_middle_click=do_action` , but I couldn't find any explanation on how to use this, and if can be used to run a script.

So my question is actually : IS IT POSSIBLE TO CONFIGURE THE MOUSE CLICK ACTION TO RUN A USER SCRIPT?

What I have so far in my dunstrc is : 

      mouse_middle_click=do_action

       [desktop_entry]
         summary= myupdate
         script=/home/.../.config/dunst/update.sh                                  

But this is not triggering the script.

**Comment by fwsmit** [comment] 2023-03-14 14:01
I'm closing this as a duplicate of #879

**Closed** 2023-03-14 14:01 UTC
